### ISSUE TITLE
Sample: Advanced features for future showcases

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j#102]
I case we want to have some more complex use-case here are some ideas for our restaurant:
* Special: Every Monday the price of all alcoholic drinks is lowered by 10% per Hour.
* Special: For a special time-range of X weeks that is announced in advanced you get the chance
for a "discount lottery". So after the time-range is closed a winning number is chosen by random
and if your bill receipt matches the winning number you get a discount (50% or your money back).
E.g. the winning number is from 0-9 and matches the last number of your receipt ID.
The bill could also carry a QR-Code so the waiter can scan it with his smartphone OASP restaurant app
and then the restaurant backend can verify that the bill in the DB really matches the criteria and
the paper receipt has not been faked.

This is not for the near future but if we need a use-case with some reasonable complexity we could pick an idea from here. If you have other ideas feel free to add.

**Comment by MarcoRose** [comment]
Most ideas presented here are very valid and need to be developed in a sustainable way. So far a community-approach for this is missing. 

So, yesterday I opened a new WIKI to colloboratively work on a comprehensive vision of the business background of the OASP restaurant example. You will find it in the new Repo: https://github.com/oasp/oasp-business-vision/wiki. Please contribute.

Closing this issue.
