### ISSUE TITLE
oasp4j-rest - Test failure under pl_PL Locale (RestServiceExceptionFacadeTest)

### ISSUE THREAD

**Issue by ghost** [oasp/oasp4j#116]
It seems that under pl_PL Locale we have a test failure:

org.junit.ComparisonFailure: expected:<...d NOT find object "4[,]711"!> but was:<...d NOT find object "4[ ]711"!>
    at org.junit.Assert.assertEquals(Assert.java:115)
    at org.junit.Assert.assertEquals(Assert.java:144)
    at io.oasp.module.rest.service.impl.RestServiceExceptionFacadeTest.checkFacade(RestServiceExceptionFacadeTest.java:106)

Can anyone else confirm it?

**Comment by amarinso** [comment]
Only for documenting, I had failing test running `mvn install` with es_ES locale.

I re-run with `mvn install -DargLine="-Duser.language=en -Duser.country=EN"` and it worked fine.

**Comment by hohwille** [comment]
@amarinso thanks for the feedback. Why dont you commit this change directly to the pom.xml so argLine always contains this locale settings? Then nobody will run into such problems again. For l10n testing we can sill provide locale explicitly...
