### ISSUE TITLE
Review security documentation

### ISSUE THREAD

**Issue by may-bee** [oasp/oasp4j#121]
We should review the current state of oasp4j-security, especially its [documentation](https://github.com/oasp/oasp4j/wiki/guide-security) and consolidate it with the current implemented artefacts.

Documentation ToDos:

* [x] Find and check Spring Security default filter chain
* [x] [Adapt vulnerabilities and protection chapter](https://github.com/oasp/oasp4j/wiki/guide-security#vulnerabilities-and-protection) to provide a full mapping of all OWASP threads and state in a new column, with with technologies and protection mechanisms the OASP tries to handle them.
* [x] Extend [Data permissions](https://github.com/oasp/oasp4j/wiki/guide-security#check-data-based-permissions) chapter to mention, that this is an important topic for data security, but it has not been investigated / implemented in the OASP (coming soon)
* [x] Extend [Check Role based Permissions](https://github.com/oasp/oasp4j/wiki/guide-security#check-role-based-permissions) to be more specific for an architecture user, what specifically someone has to do during development using method based authorization.
  * Check [Method Authorization](https://github.com/oasp/oasp4j/wiki/guide-security#method-authorization) vs. [Check Role based Permissions](https://github.com/oasp/oasp4j/wiki/guide-security#check-role-based-permissions). Duplicates?
* [x] Adapt [ Access-Control-Schema](https://github.com/oasp/oasp4j/wiki/guide-security#access-control-schema) if #122 has been finished
* [x] [Users vs. Systems](https://github.com/oasp/oasp4j/wiki/guide-security#users-vs-systems), which should focus on the different authorization mechanisms and techniques, which might handle either users or systems. Normally due to technical restrictions you will not have the same mechanisms and techniques for both kind of external access modes. -> state a seperate ticket for now.

**Comment by hohwille** [comment]
Documentation can and will always be improved continuously. However, we now have a reasonable state.
