### ISSUE TITLE
Possibilities and best practices for data-based permissions

### ISSUE THREAD

**Issue by maybeec** [oasp/oasp4j#125]
Currently, we have no best practices and reference implementations to apply permission based access on an application's data.
Nevertheless, this is a very important topic due to the high standards of data privacy & protection especially in germany. We should investigate this topic further in some of the upcoming releases.

**Comment by hohwille** [comment]
So far my suggestion would be as following:
In you application you provide an implementation for that check and make it available as spring bean.
Inject this into AbstractUc and provide protected method(s) that delegate to the actual check implementation.
In you actual use-cases that require such check you simply call the protected method manually.
This is simple (KISS) can be understood and debugged by anybody.
IMHO this is a lot better than spring-security approaches where you start "programming" the logic with annotations and contained expression strings.
The only disadvantage I see is that you can not verify that a check is done or missed as easily as with annotations using tools.

**Comment by geoffroya** [comment]
Hi all,

This topic is quite old, any update on that point?
Does anybody have information of implementations done for this matter?

I would like to add a frequent requirement on this aspect: data-based permissions must often be mixed with roles.
For example, I can have RW permission on some data, but only R on my colleagues' data.

BR

Geoff.

**Comment by hohwille** [comment]
I have resolved all this perfectly in a former project. At the moment I do not have the time to give it back (harvesting). Feel free to contact me if you have something urgent. I will try to find time to write a guide and maybe even create an isolated sample app as a demonstrating reference.
Key aspects:
Create @MappedSuperclass base-class containing the security relevant keys. Use @EntityListeners to add an entity listener to that as well as @FilterDef and @Filter to add a hibernate filter on the security relevant property so a selective WHERE clause can be extended when searching for such entities so only those are retrieved that the user is allowed to read.
Then derive the business entities from that.

**Comment by hohwille** [comment]
https://github.com/oasp-forge/oasp4j-wiki/wiki/guide-access-control#check-data-based-permissions
