### ISSUE TITLE
Apache CXF uses a wrong version of JAXB?

### ISSUE THREAD

**Issue by mmatczak** [oasp/oasp4j#140]
When starting Tomcat I got: java.lang.NoSuchFieldError: REFLECTION. The reason were incompatible JAXB versions taken by org.apache.cxf / cxf-rt-frontend-jaxws / 3.0.2:
com.sun.xml.bind / jaxb-impl / 2.2.10-b140310.1920
com.sun.xml.bind / jaxb-core / 2.2.10-b140310.1920

However according to http://mvnrepository.com/artifact/org.apache.cxf/cxf-core/3.0.2, org.apache.cxf / cxf-rt-frontend-jaxws / 3.0.2 depends on com.sun.xml.bind / jaxb-* / 2.1.14.

After I excluded the version 2.2.10-b140310.1920 and explicitly added the 2.1.14 one of com.sun.xml.bind / jaxb-*, the problem disappeared.

I am not a Maven expert, did anyone have a similar issue?

**Comment by hohwille** [comment]
As we now have new versions of flatten available, we shall give it another try.
Current state is in-acceptable if you both develop OASP and an OASP-based app on the same machine with a shared local maven repo as parent POMs with dev versions cause chaos.

**Comment by hohwille** [comment]
I have fixed the bug tonight. We can update flatten-maven-plugin to 1.0.0 as soon as it is released. Then we can close this issue.

**Comment by hohwille** [comment]
Done.
