### ISSUE TITLE
Testing services with external tools

### ISSUE THREAD

**Issue by sobkowiak** [oasp/oasp4j#145]
Currently the SOAP and REST services in the Sample are secured. To access them we need to authorize. There is no problem in web browser because we are redirected to the login page and browser remembers the access data. 

The problem begins with the external tools like SoapUI or curl. We need a guide how to access the secured services with those tools.

**Comment by sobkowiak** [comment]
I have tested this method with HttpRequester and it works. I'll test it with SoapUI and next we can provide small how-to in our documentation.

**Comment by sobkowiak** [comment]
Thi approach works after user is logged in using the login form. Then it is possible to test the service using a browser plugin (e.g. HttpResuester), because the user has already active session. Problem is while testing from external tool like SoapUI, because it is not possible to perform the form based authentication from this tool. Any help appreciate

**Comment by sobkowiak** [comment]
It is possible to disable the crfs check using the `-DcsrfDisable=true` parameter

```xml
<bean id="CsrfFilterWrapper" class="io.oasp.module.web.common.base.ToggleFilterWrapper">
    <property name="delegateFilter" ref="CsrfFilter"/>
    <property name="disabledString" value="#{systemProperties['CsrfDisabled']}"/>
</bean>
```

**Comment by hohwille** [comment]
Just to give some insights. Aljoscha or Hasham already managed to solve this with SoapUi. Further you should be aware that in devon and enterprise context the authentication is externalized so that service-calls from third-party systems do not require a HTTP session.

**Comment by sobkowiak** [comment]
It would be nice if they could write a small how-to about this

**Comment by hohwille** [comment]
If still relevant write a guide in devon4j. Please get more into action. Stop saying "someone should write a small how-to" but start writing it. The wiki can be edited by every github user. So what is preventing you from just starting such how-to?
