### ISSUE TITLE
Validation and authorization shall happen on use-cases and not services

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j#150]
While for authorization and validation it is nice to reject illegal requests as soon as possible it is however the wrong way to do that only on service level. This has to be done on logic level so other usages (batch, etc.) will also benefit from it and the application remains consistent without lots of redundancy.

**Comment by norbert-ka** [comment]
In my opinion validation should only be done at the boundary of components. It is the sole concern of the facade layer (named in the architecture guidelines, which is probably what is called service layer in OASP). At the boundary of a component we cannot guarantee that external code is complying to the component contract and therefore have to do parameter validation. Inside of the component only component code itself is calling the lower layers. We can guarantee the correctness of parameter usage with Unit-Tests there and do not need another layer of parameter validation.

**Comment by maihacke** [comment]
Validation should be part of the component. So it should be done inside the logic layer. If we do it "outside" in the service layer. Other component calls are not validated.

**Comment by norbert-ka** [comment]
It seems to me, that I do not understand what a component is in OASP. Of course validation should be done inside the component at its boundaries. Is the service layer outside of the component? A component needs an interface which in my understanding was done in the service layer. What is a component in OASP?

**Comment by hohwille** [comment]
A component consists of multiple (component-)parts that are each assigned to exactly one layer. In OASP even more specially there are never multiple component-parts of a component for the same layer.
So a component on the server side typically has a component-part for the service-layer that belongs to the component. However this has the goal to expose functionality of the component via some service technology (REST, SOAP, etc.). If a component A calls a component B within the same server application it will not use the external service interface (neither do a SOAP or REST call nor use its Java "interface" of that which has been designed with the focus of the technical service protocol). Instead it uses the component facade that is in the component-part assigned to the logic-layer.
The code in the service layer is just doing the technical service-protocol specific stuff and then also delegating to the component facade.
IMHO @maihacke is right as we can call the same functionality of a component offered by the component facade in various ways:

* indirectly via a use-case of another component
* via a SOAP service 
* via a REST service
* ...

To avoid redundancy the validation and authorization shall be implemented in one place and the right place is in the logic layer where the called use-case is actually implemented.

It would be very helpful if you have a look at our sample application. With the architecture guide we had so much misunderstandings because we always talked on abstract and theoretical levels.

Currently validation and authorization is here in a REST service:

https://github.com/oasp/oasp4j/blob/develop/oasp4j-samples/oasp4j-sample-core/src/main/java/io/oasp/gastronomy/restaurant/offermanagement/service/impl/rest/OffermanagementRestServiceImpl.java

It should instead go here:
https://github.com/oasp/oasp4j/tree/develop/oasp4j-samples/oasp4j-sample-core/src/main/java/io/oasp/gastronomy/restaurant/offermanagement/logic/impl/usecase

**Comment by norbert-ka** [comment]
Thanks @hohwille. I did have a look at the sample application and from that had the same understanding of components and component-parts in OASP as you explained.

But then @maihacke mentioned that the service layer was "outside" of the component which struck me as awkward.

In my opinion all access from outside of a component should be through an "access layer" however that layer may be called. Outside of a component can mean another server component as well as the client or another system. 

In your sample application there are two access points for every component. The service layer for the client and the "outer" part of the logic layer for other components. This "outer" part is used by the service layer too. It has no business logic, but only delegates to the "inner" part, which are the UCs. So you have a kind of sublayering inside the logic-layer.

I am the same opinion as you that in this scenario the delegator is the right place for validation!

But maybe the delegator should be part of the service layer. It has no business logic at all, only validation (in the future) and delegation. And so the service layer would be the only point of access to a component.

**Comment by hohwille** [comment]
@norbert-ka: You should be aware that there is a lot of valid literature available on the market beside the Quasar architecture guide. The common sense in the wide world is that you never call layers up-wards. This is what you and current architecutre guide are actually suggesting and what many people consider as bad-practice. We also consider principles that are widely accepted and that we can easily validate with common tools and simple rules (yes, we automatically validate the architecture defined by OASP).

Yes I am aware that the layers are within a component and it would also be possible to place the component facade in the service layer but what are we talking about then? Are we talking about which classes should hold the validation and authorization? Or are we talking about which package these classes should go to.
We had a long workshop with our lead architects and some authors of the architecture guide and aligned some aspects both in OASP and in architecture guide (not yet included in the December release - will come with the next version). I am convinced that we have a valid and profound architecture model. It might need some revisit if you are used to some little different understanding.

Can you bring in any profound argument what should be "wrong" in our architecture model? Or am I right that it is just a little different to what you have been used to in some of your former projects but there is nor right or wrong?
The OASP model is simpler but still fully scalable and more conform with the "wide world". We integrated all required aspects from the architecture guide that we have found in the workshop.

**Comment by norbert-ka** [comment]
@hohwille 
As you already said layers are inside of components. On the outside every component should have a clearly defined interface for accessing it.

And the architecture of OASP should comply with our architecture guide, since this is the way we committed ourselved to build software.

There is nothing explicitly "wrong" with the actual implementation. I just think, that the classes that compromise the interface of a component should be clearly evident when looking at the code. Having the interface of a component spread over several layers and therefore packages does not help in identifying it. 

If we decide that this is the way that should be documented for OASP and aligned in the architecture guide. If everybody knows that the "outside" interface of a component is in xxx.service.api for the client and in xxx.logic.api for other server components everything is fine.

In the end it is only a question of taste and what you are used too.

**Comment by hohwille** [comment]
Things to note:
We have SecurityRestServiceImpl that is offering security functionality not backed by actual use-cases in the logic layer. In that case we either have to keep and excuse and leave authorization annotations (however these are @PermittAll anyways) in the service or we need to create use-cases for that. As this is very technical code with e.g. only delegation to springframework I would leave it as is.

For everything else I will move the authorization and validation to the according use-case implementations.

**Comment by hohwille** [comment]
not relevant for 1.0.0 as this only affects code that is not released (sample itself, not even the application template)

**Comment by hohwille** [comment]
@julianmetzler thanks. good work :+1: 
One issue I would like to discuss: SecurityRestServiceImpl
As stated earlier we should only remove the annotations if we also extract the code to use-cases. However, my suggestion was to leave it as is. The @PermitAll might currently be kind of "optional" but it is an important documentation and we are working on architecture validation that shall check that we did not forget authorization (by checking for according annotation). Then @PermitAll tells the reader of the code as well as the code checker tools that this is intentially available to everyone (that is able to login).

Also I was planning to introduce a super-class for all services in our sample that is annotated with @DenyAll. This would make the @PermitAll required as then all methods are disallowed by default what is the best security model to prevent accidents. With this change we have to enforce this now for use-cases.
