### ISSUE TITLE
logging: Console appender should only be active in development environment

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j#156]
our logback.xml config is currently incomplete:
> &lt;!-- TODO: Console appender should only be active in development environment -->

**Comment by julianmetzler** [comment]
I added a project with a logback config file contained for logging behaviour of JUnit tests of the modules (oasp4j-testconfig). Only console logging is enabled here.
Additionally added a property to disable console logging when deploying oasp4j sample app.
