### ISSUE TITLE
logging: SingleLinePatternLayout not used anymore by logback.xml

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j#157]
SingleLinePatternLayout has been created to prevent LogForging and to better support filtering logs with low-level tools such as awk, grep, sed, etc.
However this is not yet configured anymore. It should be active for all appenders except console.

**Comment by hohwille** [comment]
I assume we need something like this

> &lt;encoder class="ch.qos.logback.classic.encoder.PatternLayoutEncoder">
      &lt;pattern>${logPattern}&lt;/pattern>
      &lt;layout class="io.oasp.module.logging.common.impl.SingleLinePatternLayout"/>
    &lt;/encoder>

**Comment by julianmetzler** [comment]
https://github.com/oasp/oasp4j/commit/754b7e3518ddfb91ff8ef8816b61a3a6ce8873c4
