### ISSUE TITLE
Sample: use @DenyAll as default on AbstractUc

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j#160]
We should try to add @DenyAll to AbstractUc and verify that if one forgets to explicitly mark a method with @RolesAllowed (or @PermitAll) then it is not available. This will force the developer to do it right and prevent security desasters.

However this can be restrictive and can cause trouble (see our current approach for authentication that is calling a use-case to retrieve the user that can not be authorized itself as the authorization requires that authentication has already taken place). So we should evaluate this and see if it works at all (is class-level @DenyAll used as default for all methods - including injection setters?) and if we can solve the described trouble.
If not possible we might close this as invalid/wontfix.

**Comment by julianmetzler** [comment]
Adding @DenyAll to AbstractUc doesn't change the behavior at all. Even if a method is missing the @RolesAllowed annotation it can be accessed. 
If @DenyAll is added to the Uc*Impl class directly it works as expected (methods without @RolesAllowed/@PermitAll can't be accessed) and has no impact on injections. Of course this would not work for the current approach for authentication.

**Comment by hohwille** [comment]
Thanks for the analysis. Adding @DenyAll to the Uc*Impl would be a general option as well as adding a check that requires to do this.
However, if we want to go for such an approach, then we have to find a solution for UcFindStaffMemberImpl (method findUserProfileByLogin). As for some reason @PermitAll does not even work here, we have to do some research or simple close this as invalid.
At least we will not add @DenyAll to AbstractUc.
Also we already have a working JUnit that does the verification, so closing as invalid is also OK.
