### ISSUE TITLE
OASP4J Documentation - Figures missing!

### ISSUE THREAD

**Issue by pfleger** [oasp/oasp4j#161]
Hello,

The newly released OASP4J documentation http://oasp.github.io/oasp4j/1.0.0/OASP4J.pdf seems to have its figures missing. For example "Figure 1.1. Technical Reference Architecture" has only its label - no image.

Best Regards,
Piotr

**Comment by hohwille** [comment]
Thanks for the feedback. You are right and it is actually a pity as this used to work all the time and exactly for the release it failed. As it seems all images from the GH pages (SVGs) are missing while other images are included. Further there are also some layout problems such as Table 4.4 on page 41.

We will fix this and try to create a new release ideally in Q1.

**Comment by hohwille** [comment]
Must have been a network issue during release generation. I regenerated from tag and images are now included.
