### ISSUE TITLE
Package of Salesmanagement DAO Test

### ISSUE THREAD

**Issue by oelsabba** [oasp/oasp4j#165]
I suggest renaming :
package :
`io.oasp.gastronomy.restaurant.salesmanagement.persistence.impl.dao`
 to 
`io.oasp.gastronomy.restaurant.salesmanagement.dataaccess.impl.dao`
 in order to keep a consistent naming convention over all package hierarchies.

**Comment by hohwille** [comment]
sure. this is a leftover from an incomplete refactoring.

**Comment by hohwille** [comment]
Thanks for the feedback - I was not aware of this
