### ISSUE TITLE
Sample: resolve warnings from Eclipse

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j#168]
When you import oasp projects into eclipse, you are faced with ~70 warnings (if HTML validation is enabled ~1000 but HTML validation of eclipse is actually non-sense - see also last commend of https://bugs.eclipse.org/bugs/show_bug.cgi?id=338759).

The java warnings should be resolved by reworking the code.

**Comment by julianmetzler** [comment]
I fixed some warnings. Most warnings left are missing Javadoc warnings in sample-core (web socket) and integration-test (Table*Builder).

**Comment by hohwille** [comment]
We should resolve as many warnings as we can before 1.1.0 and then move this issue to the next release.

**Comment by hohwille** [comment]
@fawinter thanks. Only 6 warnings left. These will be fixed in next release.
