### ISSUE TITLE
Removing mark*As methods

### ISSUE THREAD

**Issue by oelsabba** [oasp/oasp4j#172]
There are a set of mark*As methods that change the states of some Entities. 
They expect an ETO and a new state.
They load the corresponding persistent entity and update the entity's state.
An example of these is `markTableAs`.

IMHO, they should be removed as they are not intended to be used by the UI.
I suggest substituting them by save* methods.

**Comment by hohwille** [comment]
> I suggest substituting them by save* methods.

These save methods should all already exist.

**Comment by hohwille** [comment]
has been done with #173.
