### ISSUE TITLE
Logback cannot write log file on Linux platform

### ISSUE THREAD

**Issue by sobkowiak** [oasp/oasp4j#177]
Logback configuration file uses following pattern to define the log file location

    <File>${filePath}${errorLogFile}.log</File>

where `filePath` is defined following

    <property name="filePath" value="${java.io.tmpdir}"></property>

`${java.io.tmpdir}` resolves on Linux platform to `/tmp` and logback tries to write following file `/tmperror_log_lenovo_restaurant.log`, but this is not allowed and following exception is thrown

```
[INFO] [talledLocalContainer] 20:13:46,963 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[ERROR_APPENDER] - openFile(/tmperror_log_lenovo_restaurant.log,true) call failed. java.io.FileNotFoundException: /tmperror_log_lenovo_restaurant.log (Permission denied)
[INFO] [talledLocalContainer] 	at java.io.FileNotFoundException: /tmperror_log_lenovo_restaurant.log (Permission denied)
[INFO] [talledLocalContainer] 	at 	at java.io.FileOutputStream.open(Native Method)
```

`filePath`must be followed by `${file.separator}`.

**Comment by hohwille** [comment]
@sobkowiak thanks for testing and fixing. However you just reproduced the error #154 that had been "fixed" before. So we need to find a real solution for #154 - I will reopen it...
