### ISSUE TITLE
Implicit relative paths are disabled in H2 1.4.x

### ISSUE THREAD

**Issue by sobkowiak** [oasp/oasp4j#178]
Upgrade to Spring Boot 1.2.x upgrades some other dependencies like H2 database (from 1.3.176 to 1.4.183). The new minor version disables usage of implicit relative paths (http://www.h2database.com/html/changelog.html)

> Implicit relative paths are disabled (system property "h2.implicitRelativePath"), so that the database URL jdbc:h2:test now needs to be written as jdbc:h2:./test. 

We use currently implicit relative paths in our configuration file
* `database.url = jdbc:h2:target/.sample;INIT=create schema if not exists public`in `oasp4j-samples/oasp4j-sample-core/src/test/resources/config/env/application.properties`
* `jdbc:h2:tcp://localhost:${oasp.db.port}/.sample;INIT=create schema if not exists public` in `oasp4j-samples/oasp4j-sample-server-integration/src/test/resources/config/env/application.properties`

It causes following errors with the new version of H2 database:

```
[INFO] [talledLocalContainer] Caused by: org.h2.jdbc.JdbcSQLException: A file path that is implicitly relative to the current working directory is not allowed in the database URL "jdbc:h2:tcp://localhost:8143/.sample;INIT=create schema if not exists public". Use an absolute path, ~/name, ./name, or the baseDir setting instead. [90011-183]
[INFO] [talledLocalContainer] 	at org.h2.engine.SessionRemote.done(SessionRemote.java:622) ~[h2-1.4.183.jar:1.4.183]
```
 The error is described here http://www.h2database.com/javadoc/org/h2/api/ErrorCode.html#c90011. We can solve this issue by:
* using paths relative to the current user home directory, 
* use an absolute paths (not too googd idea), 
* use explicit relative paths 
* or set the system property `h2.implicitRelativePath` to `true`

> Instead, use "jdbc:h2:~/name" (relative to the current user home directory), use an absolute path, set the base directory (baseDir), use "jdbc:h2:./name" (explicit relative path), or set the system property "h2.implicitRelativePath" to "true" (to prevent this check).

**Comment by sobkowiak** [comment]
I propose to use the explicit relative paths for the both cases used in our configuration files
* `database.url = jdbc:h2:./target/.sample;INIT=create schema if not exists public`in `oasp4j-samples/oasp4j-sample-core/src/test/resources/config/env/application.properties`
* `jdbc:h2:tcp://localhost:${oasp.db.port}/./.sample;INIT=create schema if not exists public` in `oasp4j-samples/oasp4j-sample-server-integration/src/test/resources/config/env/application.properties`

**Comment by hohwille** [comment]
We need a path relative to the current directory for the tests (if we would use relative to home then jenkins or travis jobs would interfere with each other).
Using a system property is not an option. We could use Maven filtering and ${basedir} to make the path absolute.

**Comment by sobkowiak** [comment]
Another solution would be usage of explicit relative paths ad described in my last comment -- no filtering necessary.

**Comment by hohwille** [comment]
Done.
