### ISSUE TITLE
UcChangeTableImpl broken

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j#180]
Please revisit UcChangeTableImpl as it has been broken (see also #172).

**Comment by fawinter** [comment]
It is now possible to change the table and save/paste the order from the former table to the new table.
We still need to fix some issues as for now it is still possible to switch between the same table and  to change to an occupied table.

**Comment by hohwille** [comment]
@fawinter awesome :+1:
Could you create a JUnit test to verify this use-case?
