### ISSUE TITLE
sample: logback.xml not contains absolute path to tmpdir during build

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j#183]
If I build a WAR with maven and extract it, then WEB-INF/classes/logback.xml contains this:

>  &lt;property name="filePath" value="C:\\Users\\hohwille\\AppData\\Local\\Temp\\\\">&lt;/property>

**Comment by hohwille** [comment]
looks like maven filtering is active in this case what is not intended here...

**Comment by hohwille** [comment]
This will also impact the archetype result so it is actually a real bug that has to be fixed soon with a next release.

**Comment by hohwille** [comment]
Filterring has been activated on purpose as it seems:

> &lt;resource>
        &lt;directory>src/main/resources&lt;/directory>
        &lt;filtering>true&lt;/filtering>
      &lt;/resource>

Please note that oasp4j-sample-server/src/main/resources only contains logback.xml but nothing else.

**Comment by hohwille** [comment]
It appears as if logback itself is not capable to resovle this

>   &lt;property name="filePath" value="${java.io.tmpdir}${file.separator}${file.separator}"/>

But as maven resolves it you end up with a hard-coded system and user specific tmpdir in your config what is simply wrong.

**Comment by hohwille** [comment]
I disabled the filtering in maven and rebuild and cleaned. Logback can still resolve the filePath so I assume the filtering is simply wrong and has to be removed. Thats all...

**Comment by hohwille** [comment]
The reason seems to be #156. However we now see that the solution is not working as expected.

See logback.xml:

>  &lt;property name="consoleDisabled" value="${log.console.disabled}">

See toplevel POM:

> &lt;profile>
      &lt;id>deploy&lt;/id>
      &lt;!-- exclude sample from release / deployment -->
      &lt;modules>
        &lt;module>oasp4j-bom&lt;/module>
        &lt;module>oasp4j-modules&lt;/module>
        &lt;module>oasp4j-templates&lt;/module>
      &lt;/modules>
      &lt;properties>
        &lt;log.console.disabled>true&lt;/log.console.disabled>
      &lt;/properties>

**Comment by hohwille** [comment]
We should try to set log.console.disabled via application[-default].properties instead.

**Comment by julianmetzler** [comment]
An other solution would be to escape the property that should not be filtered by maven with the [maven escape string](http://maven.apache.org/plugins/maven-resources-plugin/resources-mojo.html#escapeString).

**Comment by hohwille** [comment]
> An other solution would be to escape the property that should not be filtered by maven with the maven escape string.

That would be every property except log.console.disabled.
I still think it is safer and better to disable filtering.
In the end a real system and user will have its own logback.xml.
Who would want to log to tempdir? That is all nuts. It is a valid default for a simple sample application to be installed easily and run anywhere but never suitable for production or reasonable environments.

**Comment by hohwille** [comment]
We could also have two files one for dev and one for building a reasonable WAR. Then we could switch between these files in the build via maven-war-plugin.

**Comment by julianmetzler** [comment]
The path can be set to a relative path (../logs) so the logs are stored in the logs directory of tomcat if the application runs in tomcat. 
If the application runs in eclipse the logs would go to *oasp/software/logs*. That can be changed by changing the working directory of Tomcat in eclipse. The working directory of tomcat can be changed in the corresponding run configuration. Changing the default working directory is not possible according to this [bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=301527).

**Comment by hohwille** [comment]
Seems sufficient. We can thing about providing a pre-configured launch config for tomcat with oasp4j-ide. Can you try this (create a new issue in oasp4j-ide)? Launch configs have a tab "common" that allows "Save as" set to "shared file". Then you get an XML file for it. This file can be part of the pre-configured workspace.

IMHO we can then close this issue or is there anything left?

**Comment by hohwille** [comment]
Before closing: please add a comment to explain the relative path ../logs in logback.xml.

**Comment by hohwille** [comment]
The actual problem had been fixed.
