### ISSUE TITLE
test: use modern assertions

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j#184]
we are historically used to JUnits assertNotNull, assertEquals, etc.
However there are far better ways to do assertions with
* better to read test-code
* better failure messages

There are three possible solutions:
* Hamcrest (http://hamcrest.org/JavaHamcrest/)
* AssertJ (http://joel-costigliola.github.io/assertj/)
* FEST (https://code.google.com/p/fest/#Fluent_Assertions)

The good thing about Hamcrest is that it already comes with JUnit so it should be the default choice unless we have valid arguments that another solution is really better.

After we finally decided for the solution we should refactor our existing tests using this fluent assertions. We also need to point this out in the documentation. The goal is that we really reach the developers to change their mind in writing (better) tests.

**Comment by hohwille** [comment]
I personally think AssertJ is a very good choice. Jean Philippe also used it with great success and suggest it as best choice.
See e.g.
http://www.javacodegeeks.com/2014/10/assertj-fest-hamcrest.html
https://groups.google.com/forum/#!topic/assertj/PRyTX-poBS8

**Comment by demod** [comment]
As Jörg already mentioned I'm a big fan of AssertJ. In my opinion tests using AssertJ are easier to write and read and also contain fewer errors than tests written using hamcrest or standard assertions. Also fest-assertions is dead (no commits for 2 years in the fest-assert-2.x branch).

However, AssertJ is not perfect and there are a few parts of its API that are easy to misunderstand, e.g. the javadoc and naming of 
AbstractIterableAssert.containsOnly(T...) (which you are using when calling assertThat on a List) don't tell you that it not only verifies that only the expected objects are included but also that all of them must be present. There aren't many gotchas or other feature gaps in AssertJ and I still think that it would be the best solution, however, we should be willing to commit the occasional patch to the project.

Best regards,
Philippe (Jean Philippe Neumann)

**Comment by may-bee** [comment]
I like working with Hamcrest. Nevertheless, the worst issue of hamcrest are the static methods to be used as parameters of `assertThat(...)`. It is not easy to discover functionality this way.
Especially therefore, I would prefer AssertJ as it seems to provide nearly the same functionality as hamcrest.

**Comment by hohwille** [comment]
I did also some investigation. IMHO we can already agree on:
* regular JUnit assertions like assertNull, assertEquals are dead and should be avoided for new tests.
* FEST is not a real option for the future.

The nice aspect of harmcrest is that it is already there (comes with JUnit).
However AssertJ is just a dependency away and offers better completion and usage.

As @may-bee I would also vote for AssertJ. The fluent API is way more developer friendly and the static imports with hamcrest are a pain in Eclipse (with organize imports and save actions what we usually want to have).

https://nwillc.wordpress.com/2014/08/02/assertj-stands-on-its-own/

**Comment by abuwipp** [comment]
Just had my first try with AssertJ. Seams to work fine, especially the code completion.

One learning was: AssertJ since 2.0 works only with Java 7. So I had to switch back to AssertJ 1.5.7.

**Comment by may-bee** [comment]
Nice, I am lucky that there is also a solution for legacy systems using Java 1.6, but nevertheless, this should not be focus any more. For our best practices and the sample application we should rather concentrate on AssertJ 2.0. 

I currently do not have the overview about the differences between the versions, whereas 2.0 might indicate also some API changes etc.

**Comment by hohwille** [comment]
I have also switched to AssertJ in my OSS project. Works like a charm and I can not imagine going back to plain JUnit or even hamcrest anymore.
If there are no further arguments I would consider AssertJ as choosen and will give the GO for migrating all JUnits to AssertJ.

**Comment by hohwille** [comment]
There was no further argument so far. I will close. Otherwise reopen...
