### ISSUE TITLE
test: consider JBehave

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j#185]
http://jbehave.org/

**Comment by abuwipp** [comment]
JBehave needs some configuration before it can be used. With Thucydides there comes 
a) a sufficient set of defaults in a ready, but customizable configuration,
b) a navigatable summary of the test results.
Thucydides helped me to get started with JBehave.

**Comment by abuwipp** [comment]
http://thucydides.info/docs/thucydides/_setting_up_your_project_and_organizing_your_directory_structure.html shows how thucydides and JBehave can be used to implement features test driven and with customer friendly reporting.

**Comment by Max-Goebel** [comment]
Concordion has a similar approach as JBehav/Sernity:
http://concordion.org/Tutorial.html 

It may be an alternative.

**Comment by hohwille** [comment]
On the first look JBehave looks simpler and still as promising to me. We also have at least two project references with JBehave. However, to get started we need a good example. If someone can provide one with JBehave (or any other tool) and we can then discuss on that we have a basis. Then also someone can argue what is bad about the example or what could be done better (with the same tooling or with another tooling). Then we can make progress. But we first need an experienced volunteer to setup a nice first sample.

**Comment by hohwille** [comment]
Conclusion is as following: Developers are very much used to JUnit and AssertJ. On top of that we have spring-tests and additional helpers and infrastructure up to MrChecker framework. There was obviously nobody with experience about JBehave or other such tools who had the motivation to bring it into OASP/devon with a documentation, guide and example. If that does not happen we simply consider such tools as not important or relevant enough.
