### ISSUE TITLE
Usage of CheckForNull/NonNull Annotations

### ISSUE THREAD

**Issue by dchiarad** [oasp/oasp4j#188]
This is more related to the programming model:
How about the usage of @ChekForNull and @Nonnull (from the javax package)? If you have a method which accepts some optional parameter or has an optional return values it is not possible to identify them without reading the javadoc/looking at the code. In my past projects we used one of the following two approaches:
1.	Use CheckForNull and Nonnull annotation at least for each public method (by code convention). You can use FindBugs to check if CheckForNull parameter are handled in a save manner.
2.	Use the Optional of java 8 (http://docs.oracle.com/javase/8/docs/api/java/util/Optional.html) or guava.

**Comment by may-bee** [comment]
I would go for `javax.validation.constraints.NotNull` as eclipse is able to do nullchecks by the compiler easily. Optional<?> would make the API more unreadable.

Bug be aware of this issue, when using javax `@NotNull` checks, eclipse luna, and Java8:
http://stackoverflow.com/questions/27041741/null-analysis-in-eclipse-compatibility-break-between-7-and-8

**Comment by hohwille** [comment]
http://types.cs.washington.edu/checker-framework/

**Comment by hohwille** [comment]
> I would go for javax.validation.constraints.NotNull
> Optional<?> would make the API more unreadable.

:+1: from me on that.

**Comment by may-bee** [comment]
> http://types.cs.washington.edu/checker-framework/

Sounds interesting from a researchers point of view. Nevertheless, building the source code will depend on a additional framework to be configured, which might not be appropriate for the customer as far as I got the last discussions (same for lombok). :(

**Comment by MarcoRose** [comment]
use java bean validation
do not use optional
