### ISSUE TITLE
Sample: extend example for database auditing

### ISSUE THREAD

**Issue by julianmetzler** [oasp/oasp4j#190]
From #166 we have the issue to provide a more advanced example usage of database auditing we should audit all the entities Product (also Meal and SideDish) as well as Offer.

**Comment by julianmetzler** [comment]
Because of a [bug](https://hibernate.atlassian.net/browse/HHH-9042) in envers it is not possible to audit a entity using a converter, like it is done in the OfferEntity (MoneyAttributeConverter). The current version is 4.3.5.Final fix versions are 4.3.9 and 5.0.0.

**Comment by julianmetzler** [comment]
The Envers issue is still unresolved, and the 4.3.9 release has still 20 issues in 'To Do' state.

**Comment by hohwille** [comment]
restaurant sample is dead. If not in place and still desired create a new issue in MTS:
https://github.com/oasp/my-thai-star/issues/
