### ISSUE TITLE
Add method GenericDao.forceIncerementModificationCounter(E entity)

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j#191]
Implementation:
> em.lock(entity, LockModeType.OPTIMISTIC_FORCE_INCREMENT)

Some inspirations for JavaDoc:
Enforces to increment the {@link Entity#getModificationCounter() modificationCounter} e.g. to enforce that a parent object gets locked when its children are modified.
https://blogs.oracle.com/carolmcdonald/entry/jpa_2_0_concurrency_and

**Comment by jowe** [comment]
Looks good to me and is a nice addition to the Generic DAO.

**Comment by hohwille** [comment]
Review completed. Looks good.
