### ISSUE TITLE
Add pagination support

### ISSUE THREAD

**Issue by amarinso** [oasp/oasp4j#193]
There should be at least a sample of how to work with pages of entities both on the server and client side of the sample application.

**Comment by hohwille** [comment]
Jep. We have that on the server side (see e.g. SearchCriteriaTo/AbstractSearchCriteria and AbstractGenericDao.applyCriteria(...)).
On the client side we still have discussion on the table/list widget. There is also endless scrolling as alternative to paging but paging is more KISS.

But you are completely right this is a standard demand that needs to be addressed.

**Comment by hohwille** [comment]
We should add the paging that we already have as infrastructure to our search REST services in our sample asap. We just need to find some assignee - I am currently not available for development...

**Comment by hohwille** [comment]
https://github.com/oasp/oasp4j/wiki/guide-dataaccess-layer#query-meta-parameters-and-paging
We also need something more detailed for REST as well
https://github.com/oasp/oasp4j/wiki/guide-service-layer#rest

Places where to add to sample:
https://github.com/oasp/oasp4j/blob/develop/oasp4j-samples/oasp4j-sample-core/src/main/java/io/oasp/gastronomy/restaurant/salesmanagement/service/impl/rest/SalesmanagementRestServiceImpl.java#L89
https://github.com/oasp/oasp4j/blob/develop/oasp4j-samples/oasp4j-sample-core/src/main/java/io/oasp/gastronomy/restaurant/salesmanagement/service/impl/rest/SalesmanagementRestServiceImpl.java#L106
Potentially also others such as e.g.
https://github.com/oasp/oasp4j/blob/develop/oasp4j-samples/oasp4j-sample-core/src/main/java/io/oasp/gastronomy/restaurant/offermanagement/service/impl/rest/OffermanagementRestServiceImpl.java#L122

In general for searching by criteria object a POST with the JSON of the criteria object would be better. If possible we could add a generic solution that maps the GET parameters from UriInfo to our criteria object if parameters are all flat. But that is only a nice to have.

**Comment by hohwille** [comment]
@llaszkie: can you comment if you are going for this issue?

**Comment by llaszkie** [comment]
Roger that.

**Comment by hohwille** [comment]
As a blocker on behalf of Lukasz I assign the issue to myself.
Lukasz will work on providing a pull-request.
@llaszkie thanks in advance!

**Comment by hohwille** [comment]
Can we close this issue now? Or what is left to do here? PR has been merged.
Maybe the sample app needs paging in other places as well. However, we should create a new issue in that case.

**Comment by lgoerlach** [comment]
As the client side is also mentioned in this issue, we could merge the according PR (https://github.com/oasp/oasp4js/pull/36) first.
Apart from that, I agree.

**Comment by hohwille** [comment]
We need to file individual issues in oasp4j and oasp4js in such case. An issue is assigned to a milestone that reflects a release and oasp4j and oasp4js have independent release cycles.

**Comment by hohwille** [comment]
For the sample app:
https://github.com/oasp/oasp4j/blob/develop/oasp4j-samples/oasp4j-sample-core/src/main/java/io/oasp/gastronomy/restaurant/offermanagement/service/impl/rest/OffermanagementRestServiceImpl.java#L122

still returns a plain list.

**Comment by lgoerlach** [comment]
Yes, until now, pagination support was added for order and table entities only.
Should we file a new issue for offer entities?

**Comment by hohwille** [comment]
would be great as we can then close this issue and have the paging support in milestone 1.3.0 even if the other ticket might not be complete for 1.3.0.

**Comment by amarinso** [comment]
Close this issue for milestone 1.3.0, we continue on #261
