### ISSUE TITLE
Remove Rest interface class TableManagmentRestService

### ISSUE THREAD

**Issue by amarinso** [oasp/oasp4j#200]
Hi, I could not find the case for this interface... maybe was used on a previous version and is still around?

**Comment by hohwille** [comment]
Completely true. This is a leftover and shall be deleted.
FYI: However, we will extract REST interfaces for client usage in the future (both for testing as well as for using the services in a different app - we are proposing SOA based on REST).

**Comment by hohwille** [comment]
@amarinso thanks for the feedback. Done.
