### ISSUE TITLE
complete auditing support

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j#204]
There are some leftovers from #166 especially that there is no test-case.

**Comment by julianmetzler** [comment]
There is already a issue for leftovers from auditing: #190

**Comment by hohwille** [comment]
#190 is about the sample application. This issue should track that the oasp4j-jpa-envers module shall be improved.

**Comment by hohwille** [comment]
The test that @julianmetzler created is in the sample:
DrinkDaoTest.checkAudit()

However, we need to have a test in the oasp4j-jpa-envers module itself. The current drawback is that we always have to duplicate the test infrastructure. Maybe we should switch to spring-boot sooner. Until then I think we should move the test resources to oasp4j-test but we have to ensure that this will not cause a clash with an OASP app like our sample when oasp4j-test is also on the classpath.

**Comment by hohwille** [comment]
Evers is also still missing here:
http://oasp.github.io/terms-of-use.html

**Comment by hohwille** [comment]
HHH-9042 is fixed:
https://hibernate.atlassian.net/browse/HHH-9042
in Beta1 that is released:
https://hibernate.atlassian.net/projects/HHH/versions/18450

Already beta2 is out and available:
http://repo1.maven.org/maven2/org/hibernate/hibernate-envers/5.0.0.Beta2/

We need to upgrade and properly test. After all it is still a beta and we have to take care. However, with the current bug and upgrade is definitely desired as the bug prevents usage with AttributeConverters that are suggested in OASP and commonly used.

**Comment by hohwille** [comment]
Upgrade to hibernate 5 is critical can not not be done ad hoc... So far no clear schedule for an official (non beta) release is confirmed AFAIK.

**Comment by hohwille** [comment]
Bugfix is confirmed and 5.0.0-CR1 is out. However before we upgrade to hibernate 5 we will wait for the official release and ensure that it is stable so not to be done in release 1.3.0.

**Comment by hohwille** [comment]
What needs to be done is complete #190 so add database auditing for ```OfferEntity```.
That was previously not possible due to a hibernate/envers bug. Now you can complete this and resolve this issue and #190.

**Comment by hohwille** [comment]
considered done. Restaurant sample was deleted anyhow.
