### ISSUE TITLE
Deployment pipeline

### ISSUE THREAD

**Issue by Max-Goebel** [oasp/oasp4j#206]
Currently the testing wiki recommends:
* Define a deployment pipeline!
* The deployment pipeline should have one fast running, automated validation stage to give the developers fast feedback.
* The deployment pipeline should have at least one manual validation step (user acceptance test).

Review discussions around the testing wiki showed, that OASP4J maybe should give more support for creating and running the deployment pipeline. We should discuss, if we can define a basic deployment pipeline that fits to 90% of all Java-projects (which may be customized or extended in every project). If we think, this is possible, we should define:
* Automated validation stages (For each stage: How fast should it be? Which integration levels should be included? On what type of environment it should run?)
* Manual validation stages (For each stage: Who is responsible? On what type of environment should it run? Is it mandatory for every change or for some types of changes only, e.g. UI-changes?)
* Other stages
* Which degree of transparency is required? 
* How do we achieve transparency? 

Furthermore, we must decide which kind of support OASP4J should provide. Support can be:
* Recommendations (Wiki)
* Tool configurations (e.g. GIT, Jenkins)
* Examples (e.g. Test suits for automated validation stages)

**Comment by Max-Goebel** [comment]
From Axel’s mail I extracted the following points:
* All validation stages should be automated, no manual testing. 
* OASP4J should define concrete time limits for validation steps.
* There should be a maximum of transparency. Customers should be able to understand a change’s state at every point in time.
* In order to provide such a high level of transparency, test cases should be based on user stories and the given/when/then pattern.

@Axel: Is this correct?

**Comment by Max-Goebel** [comment]
These are my remarks to these points:
* As the deployment pipeline ends with deployment into production, there must be at least one manual validation step.
* I do not think that we find time limits for stages that fit 90% of our projects
* A high level of transparency towards the customer is fine
* User stories are fine, but I’m not sure if they fit 90% of our projects. Basically, we have to types of projects:

  * Agile projects: They often work with user stories anyway. The problem is that an user story does not concern anyone after it is finished. As a consequence, there is a spontaneous growth of user stories. If user stories should be provide transparency for regression tests, there would have to be something like a “user story architecture”, but I didn’t see that in any project. Furthermore, product owners will write user stories in other tools than eclipse (Jira, Excel…), so there is a discontinuity of media.

 * Non agile projects: Mostly the system behavior is defined by long lists of requirements and/or use case specifications. I do not think that it is a good idea to transform these specification types into user stories, because this would cause shadow requirements engineering. 

With JBehave/Serenity we can support many types of requirement-artifacts (see https://github.com/oasp/oasp4j/issues/185 ).  But we should not dictate that a special kind of requirement artifact (like user stories) must exist. 

In most projects, requirements are managed in a requirement management tool or simply in MS Office documents. If these requirements should be used in JBehave/Serenity, they have to be kept redundantly. So project will think about tool integration, but this should be not in the scope of OASP4J (at the current stage).

**Comment by aburghcap** [comment]
Hier die Vorschläge nochmal im Original:
For Continuous Delivery / DevOps it is key to have an automated, reliable quality assurance (see section Deployment Pipeline). All changes should target the following “vision”: 
Test suites automatically executed by the Continuous Delivery Pipeline insure what requirements the system is expected to fulfill and whether they are fulfilled. Stakeholders should be able to inform themselves about this by reading the appropriate test report.
To make bugfixing fast and easy Continuous Integration should give feedback in under 10 minutes about whether changes could be integrated or why not. For that low level requirements and technical details should be insured in clean unit  tests taking at most 50 ms (200 tests/s, 12000 tests/min, ~80000 unit tests in the Continuous Integration job including what else needs to be done). Therefor unit tests mock out underlying dependencies.  
Code that inevitable depends on time-consuming subsystems (filesystem, database, UI, …) are partitioned into different test suites that the Continuous Integration server can run after the first “stage”. Bob Martin’s “Clean Architecture” helps to minimize the need for this kind of tests.
Unit tests are the fastest way to insure detailed requirements and should be considered as default despite the language or environment to be used. By now for any relevant language there is a unit testing environment, especially for JavaScript.
Based on that module tests and different kinds of integration tests insure that units and modules correctly work together. Beyond that acceptance tests treating the production-like deployment as a white box insure the main requirements.
Requirements are negotiated as user stories and made testable by adding scenarios. These scenarios are structured following the BDD style – given / when / then – to be well-understoud. They can be formalized using language Gherkin. The scenarios are than coded as test cases.
Test automation comes not for free. But treat test automation as what a cordless screw driver is for a mechanic craftsman – your tool to build the right software right. For our customers quality is nothing negotiatable. And bugfixing is more expensive than test-automation.

**Comment by MarcoRose** [comment]
There is a basic build/deployment infrastructure being used for OASP. However, this is not part of the product. DevOps is a separate very important issue. But this is out of scope for OASP.
