### ISSUE TITLE
oasp4j sample-server archetype misses *-server-integration project

### ISSUE THREAD

**Issue by may-bee** [oasp/oasp4j#208]
A users observed that the currently release version v1.1.0 of the oasp4j archetype misses the *-server-integration project, when generating a new inital maven project using the archetype.

**Comment by hohwille** [comment]
Our integration test strategy based on cargo failed to work as expected.
We are about to create a new and stable solution till the next release. The *-server-integration project will probably die out and will be deleted after the new solution is in place.

**Comment by amarinso** [comment]
> We are about to create a new and stable solution till the next release.

How are  we going with this issue? 

I've created a PR #262 because the integration test where failing. The project is even disabled on oasp-ci, is there anything planned to be aware of? What about the "maven-archetype v1.1.1" reference? can we help here?

**Comment by hohwille** [comment]
To summarize the state: our current approach with integration tests has more or less failed and never worked stable. We had hanging processes in jenkins, etc. We first need to resolve that issues and have a reliable strategy before pulling this out. In case we switch to spring boot, we can have the integration tests in the same project and use our existing OASP JUnit categories for Subsystem and Systemtests with the provided mave profiles to activate them. Then you can configure your nightly build to run all tests while CI build only runs unit- and component tests. That is all there but we do not yet have reliable subsystem or systemtests yet in our sample.
So in the end we might one day delete the *-server-integration project and mark this issue as invalid. We will see.

**Comment by MarcoRose** [comment]
gets resolved with spring boot #232
