### ISSUE TITLE
build and release v1.1.0 documentation

### ISSUE THREAD

**Issue by may-bee** [oasp/oasp4j#209]
Currently the v1.1.0 PDF documentation has not been released on the webpage.
We should catch this up.

**Comment by hohwille** [comment]
I do not know what you mean?
http://oasp.github.io/oasp4j/1.1.0/

**Comment by may-bee** [comment]
It has been fixed meanwhile.

**Comment by hohwille** [comment]
I was fixed from the start :)

But I just found that the homepage was not updated to link to 1.1.0 PDF instead 1.0.0. If fixed this and also updated the docs:
http://oasp.github.io/oasp4j/
https://github.com/oasp-forge/oasp4j-wiki/wiki/oasp-release

**Comment by may-bee** [comment]
Yes, the homepage issue was what I was pointing to.
