### ISSUE TITLE
logback.xml: logging directory is relative to PWD of container start script

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j#213]
As reported in #210 the logging directory is relative to PWD of the start script. That is an unacceptable situation. We need to find a reasonable solution and as the combination of tomcat and logback should be quite common there should be something available on the web how to resolve.
However, the solution should be portable and not only work with tomcat in general.

**Comment by hohwille** [comment]
Please note that in any reasonable setup the operators will override the logger configuration anyways and not rely on a file bundled in a WAR file.
So just copy logback.xml to $CATALINA_BASE/lib and modify as desired.

**Comment by amarinso** [comment]
We could use the application.properties file to configure where to put the log files by using `<property resource="config/env/application.properties" />` on `logback.xml` we can make use of variables to configure the `${filePath}`

```xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Configuration file for logback -->

<configuration scan="true" scanPeriod="60 seconds">
  <property resource="config/env/application.properties" />
  <property name="filePath" value="{appLogsPath}"></property>
  ...
```

and then make explicit on the `application.properties` the path for the files:

```properties
appLogPath=/var/lib/tomcat_instance1/logs
```

**Comment by hohwille** [comment]
good suggestion. We should take this approach.

**Comment by hohwille** [comment]
Still the question would be what we use as default. Maybe we will keep "../logs/" but then everybody can override via application.properties without touching/replacing the entire logback.xml if he wants to keep the other stuff bundled with the release. This way we could also resolve the switch for console logging.

**Comment by hohwille** [comment]
Is there a general variable such as CATALINA_BASE that we should rely one? Maybe even one that is JEE conform and would work with all containers?

**Comment by hohwille** [comment]
Done. Someone could explicitly test the latest archetype on develop branch as I did not test explicitly but should work OOTB.
