### ISSUE TITLE
Create ear package for oasp projects

### ISSUE THREAD

**Issue by nelooo** [oasp/oasp4j#215]
Maybe would be a good idea to allow ear packaging in OASP project, due to requeriments for any customers.

This packaging will support specific deployment descriptor files and will include the existing war module in the sample application.

If you consider this issue, I can modify the sample application to allow ear packaging, maybe as a maven profile or maybe as a new project.

What do you think about this requeriment?

**Comment by MarcoRose** [comment]
Yes, it was agreed we want to have this.
But, can we do this additionally to a war deployment? If not it may be better to develop this feature in the devonfw-repo.

**Comment by nelooo** [comment]
I think this will be additionally to war deployment, so I will start working on this issue in the OASP4J project.

If there is any problem to add to war deployment, I will change to devonfw-repo instead of oasp4j.

**Comment by hohwille** [comment]
Using a profile as you suggested should work:
http://stackoverflow.com/questions/8247720/changing-packaging-based-on-active-profile-in-pom

The default should remain a WAR. However, we should be highly aware that in a real project you would decide for one of the two. Actually really using the profile beyond the demonstration purpose would be insane and you can read enough warnings in the maven docs about profile dependent build logic. E.g. assume you would deploy both for the same version what would end up in chaos.
So please leave an XML comment.
Further if in the end there would be just one or two keywords to change, then better consider to address this in the documentation as the profile is only adding extra complexity (and we are creating a maven archetype from our sample that is to be used by all the projects).

Thanks in advance for your investigations and support.

**Comment by nelooo** [comment]
Finally I decided to create additional project to generate the ear packaging, due to allow applications customize the ear package and use all the power of enterprise applications (additional web applications, ejb modules, customize the enterprise application descriptior, …).

In order to simplify the solution, I modified the actual archetype to allow final user add ear packaging or not. To add this capability to archetype, I take the velocity engine used by maven archetype generator combined with a new archetype property named earProjectName (default value is dot (.), and imply not to create ear project). If you would like to create ear packaging, the suggestion is to set earProjectName property a value equivalent to ${artifactId}-ear.

A sample using the new archetype:
                - For only war packaging (argumens before archetype:generate identifies oasp artifact):
                                mvn -DarchetypeVersion=1.1.0 -DarchetypeGroupId=io.oasp.java.templates -DarchetypeArtifactId=oasp4j-template-server archetype:generate -DgroupId=archetype.it -DartifactId=basic -Dversion=0.1-SNAPSHOT -Dpackage=it.pkg
                - For war and ear packaging (argumens before archetype:generate identifies oasp artifact):
                                mvn -DarchetypeVersion=1.1.0 -DarchetypeGroupId=io.oasp.java.templates -DarchetypeArtifactId=oasp4j-template-server archetype:generate -DgroupId=archetype.it -DartifactId=enterprise -Dversion=0.1-SNAPSHOT -Dpackage=it.pkg -DearProjectName=enterprise-ear 
 
Based on the value of earProjectName, the pom’s generated project, add the ear module or not.

I modified the archetype project unit testing, to generate ear packaging and only war packaging.

Please tell me if this solution is all right for you or maybe we must look for another solution.

**Comment by hohwille** [comment]
:+1: sounds great. Will you provide the change as PR?

**Comment by nelooo** [comment]
Done

**Comment by MarcoRose** [comment]
Super! I guess you left some documentation in the Wiki too?

Viele Grüße
Marco
_______________________________________________________________________
Marco Rose
Custom Solution Development | Application Services

Capgemini | Offenbach
Phone: +49 69 9515 2228 – Mobile: +49 170 7913023
Fax: +496982901200 – e-mail: marco.rose@capgemini.com
www.de.capgemini.com<http://www.de.capgemini.com/>

Berliner Str 76, 63065 Offenbach, Germany
People matter, results count.
_______________________________________________________________________
