### ISSUE TITLE
Using component facades

### ISSUE THREAD

**Issue by MarcoRose** [oasp/oasp4j#219]
From: Jörg Hohwiller

we are getting into very fundamental discussions about  architecture in general.
From what I learned and what you can find on the web and books about architecture a DAO is responsible for the operations around one persistence entity.
That is what we are doing in OASP: One DAO per Entity.
Then in simple CRUD we have two Use-Cases per Entity UcFind<Entity> and UcManage<Entity>. However, this is a convention and you are free to extend to your needs. Business logic can get really complex and tough as we all know…

We used this design in Germany for years with great success and long before CobiGen was ever invented.

Further, the REST-Service Implementation is the same as the Component-Façade implementation. It is a Façade and has not real logic than delegation (and obviously protocol transformation). So I do not agree to your argument (from the earlier mail) that this is an asymmetric pattern.

Further to you and Simon:
I learned that in the end it is simpler to have one pattern for all kinds of applications rather than saying well wenn its small and simple you do A and when it gets complex and big you do B. That is always causing more confusion and waste of design energy as you can never say when something grows from small to big or from simple to complex.
Maybe in Germany we did so complex architectures in the past 15 years that this already seems so easy what we are doing in OASP.

But what does your components do and how do you tailor your components if there is one entity per component and all use-cases can be maintained in a single implementation class. If we are talking about a system with 1-10 entities we do not have to talk and care about architecture at all, that is peanuts.
In such case you would probably manage to maintain your system without layering and separation of components at all. Just use hibernate directly in your services. But when your system grows you will die!
I am talking and thinking about bigger systems. And even when there are 50 entities and 200 use-cases I still consider a system as small.

However, I totally agree to your suggestion that we should get more feedback from different countries, projects, developers.
I have a strong personal opinion on these topics as you might read from my mails, but I am totally open hear what the community is saying and learn from it.

For me it was quite surprising that you all want to discuss about the approach 2. that was not in question for me at the beginning and I am still not convinced.

-----------------------------------------------------------------------------------------------------
From: Marin Soler, Angel Luis 

Reviewing the sample application I see another "anomaly" to the pattern, let me explain:

- The logic interface is nicely separated in UC and that way different teams can work on different classes
- When doing the implementation, all the UCImpl refer to the same DAO, this way only one class is doing all the implementation of the use case. 
- Maybe this is only because it is the way CogiGen is generating the code but... shoudn't be there also different DAOs for each UC?
   - If not, we can not use the argument of separate files to support different teams working on same location.

I would vote for Simon proposal of starting small and having a chapter on "how to scale" where more advance packaging organization is used.

We should modify the generator for having this "dual" model... something I suppose won't be trivial.
regards,

----------------------------------------------------------------------------------------------------
From Spielmann, Simon

I was talking about the advantage of “grouping” all UCs into one componenten façade.
This allows to inject a single interface (the component interface) into other components. This is less work than injecting every single use case you need.
The bigger advantage is about readability. Since all uses cases are called on the components interfaces you could easily see which components they belong to:

With component interface:

customermanagment.createCustomer(..)
….
customermanagement.assignCustomer(…)

Vs without component interface:

createCustomerUc.create(…)
assignCustomerUc.assing(…)

For the code completion. If you do completion on customermanagment you will the all UC-Method Customermanagement offers. If you don’t have this façade you have to browse to the customermanagement package and see what UC-Interfaces are there.

-----------------------------------------------------------------------------------------------------
From: Marin Soler, Angel Luis

I can agree on the 5 minutes per component overhead... when writing.

But time is spent more time reading code than writing it and having all this model on the head is where I see the complexity.

I don't understand well what you mean with less injection hazzle, and also the code completion advantage you mentioned... isn't it the same if you have one interface and implementation? use cases (as a group) doesn't show up on the IDE when the component interface is used (or I am missing something here)

Other concern of mine is that this separation in UC is good for a project on a waterfall model where you have defined up-front almost all the project UC. But in a more agile environment you will be doing a lot of refactoring to re-group methods into new-or-renamed UC interfaces as project evolves... or you incur on the risk of ending with one interface for each method implementation in order to have greater flexibility (not very KISS)

For clearly seeing the advantages of the pattern we can also showcase the intended use of the individual UC on the sample application. Maybe I've haven't understood completely your ideas, let me share an example from the sample app.

- In UcManageTableImpl there is a need for finding an opened order for a table. 
- In the sample, Salesmanagement is injected as a dependency
- By having the individual UC... should have been better to have only UcFindOrder injected?

-----------------------------------------------------------------------------------------------------
From: Spielmann, Simon

no time to start yammer discussion right now, but want to add some pro arguments for those facades:

They speed up development because of less injection hazzle
They greatly improve code readability because invoking use cases of other components is every explicit. You could nicely see which component offers the uc.
You could easily the which use cases offers a component (by code completion on the component interface)

So leaving out those interfaces could save maybe 5 minutes per component. I can't see a real efficency gain here.

-----------------------------------------------------------------------------------------
From: Marin Soler, Angel Luis

I think you are right about scaling when it is a BIG application and there is a lot of people involved on the same project. 

But we have to think also on smaller projects and free them for such added complexity. 

90% of our projects would be fine having one interface and one implementation. (Is this an Spanish singularity? how is it in other countries? or per engagement? maybe we need more information to better align the solution. )

Also, if we are exposing the interface through a service... we are already doing all the implementation on one single class!! (in this case OffermanagementRestServiceImpl). So 
we are avoiding the problem in one layer but not in others... which makes it worse when trying to debug an application because it is kind of asymmetric. (Maybe we can think on having the components/usecases grouping also on client side)

I think the problems about working on the same location should be easily managed as the code for each UC is quite contained and most of the time an automatic merge will do (theoretically, of course on real life there are always conflicts)

So... how can we offer a solution for large (or very large) projects and more contained ones?

I think we can showcase both approaches on the sample applications clearly documenting which usecase (no pun intended) is trying to solve.

I think this will impact also the as we should automate both alternatives.

-----------------------------------------------------------------------------------------------------
From  Hohwiller, Jörg
 
we should clearly distinguish whether we are going to question 
1.     the existence of the component interface and its implementation as a simple delegation façade
OR
2.     the existence of the individual use-case interfaces and their implementations
 
When you are saying
> In the simple example of Tablemanagement we would spare 3 interfaces. Do we need them for other reasons but to constitute the component façade?
 
you might imply 2. or you might not have understood the pattern and the code yet.
For me 2. is out of question as this would mean that the entire component implementation is forced to be in a single class.
IMHO we should only discuss about 1.
 
To make things clear I just created a UML diagram with drag & drop from our offermanagement component.
 
 
Here we have Offermanagement and OffermanagementImpl to be questioned by 1.
If we would drop this then other components using logic of the offermanagement component would have to inject individual use-cases. 
Pro:
•         We would save the upfront effort to create and maintain the façade.
Contra:
•         We often might need multiple injections instead of just one and we have to find the one we actually need.
•         If the internal structure (e.g. cut of use-cases) of the component offermanagement would change for some reason this would impact using components and hence might cause some extra effort.
 
I personally think this is more a less a decision of flavor. For true KISS you could argue for 1. and it would not really hurt.
As you can see from the Contra side there are however few good reasons why the pattern was invented in Register-Factory (and we even improved and simplified the original RF approach that used redundant signatures between façade and Uc where we use interface inheritance also to centralize JavaDoc).
 
However, 2. would mean to drop all Uc* classes and interfaces and have the ENTIRE implementation in OffermanagementImpl. This is a design hell that is not going to scale. Assume the developer conflicts when all are working in the same location. Assume the lines of code of that implementation and the effort to find the right spot to do a change.
This is massively violating Separation of Concerns.
 
I hope the discussion is clear now.
 
BTW: we tend to discuss too much via Email. Lets do all of this on yammer and where suitable in github issues instead.
 
Regards
  Jörg

----------------------------------------------------------------------------------------------------- 
From: Rose, Marco 
 
Spanish team – out of experience with Devon Espana – questioned component facades for efficiency reasons and to simplify composing.
 
(We discussed the benefits of the generator here already..)
 
In the examples, there is only little coding involved, still – what happened if: the component interface was only documented by the public methods of the implementing component class?
 
In the simple example of Tablemanagement we would spare 3 interfaces. Do we need them for other reasons but to constitute the component façade? 
Is there more discipline to design a quality component interface when one has to write an interface explicitly? (I’d say yes).

**Comment by amarinso** [comment]
I've done a survey on our current projects and all of them are over 50 entities, the biggest one (that we have control from Valencia office ) has been with 649 entities (a single app for a water distribution utility)

We haven't found problems even with projects of this size (just saying, it was a curiosity of mine knowing the size of our projects)

Establishing the "worst" case scenario as the baseline for all projects maybe is a big penalty for the majority of the projects.

My proposal is to have both options, and make the generator deliver both solutions.

Also a project should choose only one option and not mix both. I agree that it is better to do things only one way (which reminds me the topic of using POST on REST for uniformity :-)

**Comment by amarinso** [comment]
As we have agreed on simplification of the logic layer now we have to change the sample app to reflect this.

Should we keep one business component on the sample to show the alternate way? For example `sales management`which implements up to 7 UC and seems a good candidate to show complexity.

This should have the **bad** effect of introducing some redundancy on the sample because both `AbstractComponentFacade` and `AbstractUC` may have duplicated code.

**Comment by hohwille** [comment]
> This should have the bad effect of introducing some redundancy on the sample because both AbstractComponentFacade and AbstractUC may have duplicated code.

What would be duplicated actually? I do not yet see what you mean...

**Comment by amarinso** [comment]
Since the UC extend AbstractUC with contains a constant and some methods, those should be added to AbstractComponentFacade.

But we can move the constant to other class and refactor the methods on an utility class thus avoiding the duplication.

**Comment by may-bee** [comment]
I am really concerned of what is going on here.
I just tried to implement a reference implementation for our oasp school and now I see this larget OffermanagementImpl class with around 35 methods already!

There is so many boilerplate code, that I even would not find the method I am interested in fastly.
Reading the discussion (just what is available here in GitHub), I was not quite sure, that we agreed on removing all the use case implementations. IMHO the OffermanagementImpl class as it is now it not easily readable and maintainable anymore. My first intuition was to sort the methods to get a better overview...

**Comment by amarinso** [comment]
In my opinion the faster way to move around code is to use what the tools already provide us.

In case of Eclipse just using the shortcut "Ctrl + O" shows the **_outline_** of the class where you can filter just by typing:

- the start of the method
- using an *
- using CamelCase notation

I think this is faster than knowing in which interface/class is the method you are looking for. But of course this is different for every person.

**Comment by may-bee** [comment]
Yes, but as far as I got it now, it is a personal opinion.
Both approaches can be implemented and it seems, that we are focusing on the component interface implementing all logic as standard case.
The use case distinction might be more interesting for more complex components.
That is ok for me.

**Comment by amarinso** [comment]
Maybe we should better refactor this class as it deals with products and orders... I agree that 35 methods and 5 different Daos... is a bit too much (even if you can move around fast)

**Comment by amarinso** [comment]
>The use case distinction might be more interesting for more complex components.

@may-bee The idea is having the complex approach pattern of use cases as an extension of the OASP pattern on the IP repository

**Comment by may-bee** [comment]
I do not think that "devide and conquer" (the use case approach) is an IP feature.
It is just human nature and thus we should not provide non-maintainable code in the OASP respository. But the more important argument to also implement the use case approach in the OASP sample application as far as needed due to complexity of components, is the fact, that we want to keep the OASP and IP sample application somehow in sync. 
If you distinguish the sample application on this level, you will get serious merge problems, e.g. from the latest OASP sample application to the IP project. 

Finally, I would vote for the following solution for the oasp4j-sample-application as well as for the analogous IP project:
Lets implement the tablemanagement as well as the salesmanagement with the more simple approach and lets implement salesmanagement as well as offersmanagement with the use case driven approach as these components have grown to a level, where it gets somehow nasty to maintain the one-in-all-component-facade.

**Comment by amarinso** [comment]
Currently, it is the SalesManagement the one still using the UseCase approach as it already extends 7 interfaces.

As for the "serious merge problems" you refer, we are indeed struggling with it. Currently, the IP sample is using the oasp-sample-core jar as dependency to not duplicate the code... but it only get things more complicated than it should be. We will have to re-think our sample strategy.

I will close this issue now for the release as we already have both approaches on the sample app. Maybe we should explain this duality on the tutorial or the document that should explain the sample application (something that currently we don't have)
