### ISSUE TITLE
replace Criteria API with dynamic queries using QueryDSL 

### ISSUE THREAD

**Issue by MarcoRose** [oasp/oasp4j#220]

**Comment by lparczew** [comment]
Seems like already fixed ( commit id : af8e84).

**Comment by MarcoRose** [comment]
Still used in e.g. 
io.oasp.gastronomy.restaurant.offermanagement.dataaccess.impl.dao.OfferDaoImpl

**Comment by maihacke** [comment]
Fixed by PR #411
