### ISSUE TITLE
Spring DI with UC and facade

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j#228]
As discussed in https://github.com/oasp/oasp4j/pull/225 and elsewhere we have some struggle with Spring DI (that seems to behave different in travis, etc.).
Maybe we should just use qualified injections using ```@Inject @Named("Uc...")``` and everything would be fine. I wanted to avoid it for simplicity but if this causes problems we should go for it.

Please note that there was also a discussion about omitting the facades entirely or about omitting the separation into use-cases entirely.

**Comment by hohwille** [comment]
> The problem is the circular dependency between component interface and the components use cases. So the easiest and most compliant fix will be reimplementing the component interface rather than letting the component interface inherit all use case interfaces. Nevertheless, this also introduces redundancy.

I prefer my suggestion above which is easier and better IMHO.

**Comment by hohwille** [comment]
I would also suggest to roll back the autowire config change:
https://github.com/oasp/oasp4j/commit/0b5ecafda5933731d22c96324bec9dbe503c55c0

**Comment by hohwille** [comment]
As it seems there is an other approach already applied:
https://github.com/oasp/oasp4j/commit/af7b35741e6ea1f49d1b17336492ea32ec37f4e4

However, if we can use CDI standard as solution in preference to spring specific annotation this would be better as then the solution is portable for JEE.

**Comment by amarinso** [comment]
In Java EE we have Qualifiers to further refine what bean to be injected. I see `@Primary ` as a Spring way to do it. But maybe it also supports the standard  `javax.inject.Qualifier` annotations.

**Comment by hohwille** [comment]
https://github.com/oasp/oasp4j/pull/231
I tried it with ```@Named```
We could also create a Qualifier ```@UseCase``` what would avoid the String constants. Also worth a shot.

**Comment by hohwille** [comment]
see https://github.com/oasp/oasp4j/pull/233
Can someone verify that this is better/simpler and we should merge the PR and we can close this issue?

**Comment by hohwille** [comment]
All done now.
