### ISSUE TITLE
avoid redundant version numbers in POMs

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j#230]
Currently we have versions like ```spring.boot.version``` redundant/duplicated in POMs:

* https://github.com/oasp/oasp4j/blob/develop/pom.xml#L27
* https://github.com/oasp/oasp4j/blob/develop/oasp4j-templates/oasp4j-template-server/src/main/templates/archetype-resources/pom.xml#L12

We can try to solve this by using a variable in the second POM that gets replaced when the archetype is build. However, we can not use maven filtering as then various other variables would get resolved in an undesired way.

**Comment by hohwille** [comment]
Maybe we do some additional ANT hack for that...

**Comment by sobkowiak** [comment]
I think you can define how the placeholder to be teplaced look like. You can define the delimiters [ and] for the placeholder, and next use something like this $[spring.boot.version].

**Comment by sobkowiak** [comment]
Look at this sample https://github.com/apache/karaf/tree/master/archetypes/feature. There is a delimiter ^ defined in the archerype project pom and next a variable ^project.version^ is used in the archetype resources pom file

**Comment by hohwille** [comment]
@sobkowiak :+1: awesome. Thanks for the hint
https://github.com/apache/karaf/blob/master/archetypes/feature/pom.xml#L64
cool feature. This will be our solution...

**Comment by sobkowiak** [comment]
I have merged the pull request from @amarinso  and performed some changes to solve the build error. I think, this theme can be closed.
