### ISSUE TITLE
validation: update documentation and improve sample

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j#237]
From #218 there are some little left overs that should be completed for the next release.

**Comment by amarinso** [comment]
We have documentation and samples for the alternate client already done (we have a CRUD example that does validation on the input form)

@lgoerlach are we going to provide a CRUD example on the OASP4JS sample application for this release (1.3.0)? if not we can close this issue here and open an issue on OASP4JS repo

@hohwille can you give more details for this on your comment of #218 ?

>  We have to ensure that the locale on the client is part of the metadata so the server locale for the request is in sync

Do you mean sending the locale on each request?

**Comment by hohwille** [comment]
> Do you mean sending the locale on each request?

There is a general default defined by HTTP how client and server negotiate the locale (Accept-Language, etc.). However in extension to that an app can have a user profile where each user might select the locale in his profile.
So my suggestion would be that we derive the locale on the server from the defaults. Works OOTB with spring. Just use LocaleContextHolder to retrieve Locale. However, we need to define how the client can propagate an explicit locale that was choosen by the user and should override the defaults (at can be odd if you are using an internet café browser). The easiest way is to save that in the user-profile on the server side and so the server can retrieve this during login and update LocaleContextHolder.
See also http://www.w3.org/International/questions/qa-accept-lang-locales

**Comment by hohwille** [comment]
We need to align this with the way that sencha and angular determine the locale and get configured. Some frameworks accept e.g. ```?locale=es``` in URL.

**Comment by lgoerlach** [comment]
> @lgoerlach are we going to provide a CRUD example on the OASP4JS sample application for this release (1.3.0)? if not we can close this issue here and open an issue on OASP4JS repo

To my knowledge, there is no such example in the OASP4JS sample application.
At the moment, every update or delete operation in the client is "hardwired" with dropdown menus or buttons, so there is no CRUD example with forms where the user could enter invalid data.

**Comment by amarinso** [comment]
For our Sencha client, the application starts on a default language (say en_EN) and then provides a customizable mechanism for overriding the language resolution (it should come from the `/currentuser` request after the login process). 

If the retrieved language is not the same as the current one then a cookie is stored and the page is reloaded. 

On reloading, the resolve mechanism uses the value from the cookie to properly set the locale for the Javascript.

**Comment by amarinso** [comment]
Ok, if we don't have OASP4JS CRUD example I think we can close this issue and continue the locale on #245

**Comment by hohwille** [comment]
> so there is no CRUD example with forms where the user could enter invalid data.
For the restaurant in general:
* The user could create a table with a number already occupied
* The user could enter an invalid table number (<= 0)
* When we update the reservation and do not start with a calender widget the user has to enter a time-range (from/to). In such cases we have cross field validation - "from" must not be after "to". Further the reservation data must not be in the past.
* ...

**Comment by hohwille** [comment]
If we e.g. store the locale in a cookie, shall we then define a standard way how the client shall send that to the server? Otherwise client and server locale could be out of sync.
On the other hand if we say the locale is a property of the user profile then both client and server have to consider the locale from there (and IMHO a cookie is not required).

**Comment by hohwille** [comment]
@amarinso we can close this issue. It is better to create individual issues for specific aspects. Such as "redesign reservation to time-slots" or "add constraints for table number".
If the documentation has already been updated, we should close this one.
