### ISSUE TITLE
build fails: Archetype IT failed: Cannot run additions goals.

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j#238]
I can not perform the release. The build fails:

> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary:
> [INFO]
> [INFO] oasp4j-templates ................................... SUCCESS [  0.668 s]
> [INFO] oasp4j-template-server ............................. FAILURE [  4.208 s]
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 5.121 s
> [INFO] Finished at: 2015-05-25T15:41:38+02:00
> [INFO] Final Memory: 14M/35M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:2.2:integration-test (default-integration-test) on project oasp4j-template-server:
> [ERROR] Archetype IT 'basic' failed: Cannot run additions goals.
> [ERROR] Archetype IT 'enterprise' failed: Cannot run additions goals.

**Comment by hohwille** [comment]
IMHO this is caused by #224
However, I can not easily track it down at the moment... :(

**Comment by nelooo** [comment]
I will try to solve the issue ASAP.

**Comment by hohwille** [comment]
This is what maven says with ```-X```:

> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:2.2:integration-test (default-integration-test) on project oasp4j-template-server:
Archetype IT 'basic' failed: Cannot run additions goals.
Archetype IT 'enterprise' failed: Cannot run additions goals.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException:
Archetype IT 'basic' failed: Cannot run additions goals.
Archetype IT 'enterprise' failed: Cannot run additions goals.
        at org.apache.maven.archetype.mojos.IntegrationTestMojo.execute(IntegrationTestMojo.java:268)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more

**Comment by hohwille** [comment]
@nelooo thanks for looking at this. I also tried to manually run the test projects in ```target/test-classes/projects/basic/project/basic``` and then ```mvn install``` succeeds. Strange...

**Comment by hohwille** [comment]
Maven is actually not really helpful with his log and error messages.
This is what comes before the build error:

> [INFO] ----------------------------------------------------------------------------
[INFO] Using following parameters for creating project from Archetype: oasp4j-template-server:1.2.0-SNAPSHOT
[INFO] ----------------------------------------------------------------------------
[INFO] Parameter: groupId, Value: archetype.it
[INFO] Parameter: artifactId, Value: basic
[INFO] Parameter: version, Value: 0.1-SNAPSHOT
[INFO] Parameter: package, Value: it.pkg
[INFO] Parameter: packageInPathFormat, Value: it/pkg
[INFO] Parameter: version, Value: 0.1-SNAPSHOT
[INFO] Parameter: package, Value: it.pkg
[INFO] Parameter: earProjectName, Value: .
[INFO] Parameter: groupId, Value: archetype.it
[INFO] Parameter: artifactId, Value: basic
[WARNING] Don't override file C:\Projekte\oasp\workspaces\main\oasp4j\oasp4j-templates\oasp4j-template-server\target\test-classes\projects\basic\project\basic\.\pom.xml
[INFO] Parent element not overwritten in C:\Projekte\oasp\workspaces\main\oasp4j\oasp4j-templates\oasp4j-template-server\target\test-classes\projects\basic\project\basic\basic-core\pom.xml
[INFO] Parent element not overwritten in C:\Projekte\oasp\workspaces\main\oasp4j\oasp4j-templates\oasp4j-template-server\target\test-classes\projects\basic\project\basic\basic-server\pom.xml
[INFO] project created from Archetype in dir: C:\Projekte\oasp\workspaces\main\oasp4j\oasp4j-templates\oasp4j-template-server\target\test-classes\projects\basic\project\basic
[INFO] Invoking post-archetype-generation goals: install
[INFO] Processing Archetype IT project: enterprise
[INFO] ----------------------------------------------------------------------------
[INFO] Using following parameters for creating project from Archetype: oasp4j-template-server:1.2.0-SNAPSHOT
[INFO] ----------------------------------------------------------------------------
[INFO] Parameter: groupId, Value: archetype.it
[INFO] Parameter: artifactId, Value: enterprise
[INFO] Parameter: version, Value: 0.1-SNAPSHOT
[INFO] Parameter: package, Value: it.pkg
[INFO] Parameter: packageInPathFormat, Value: it/pkg
[INFO] Parameter: version, Value: 0.1-SNAPSHOT
[INFO] Parameter: package, Value: it.pkg
Mai 25, 2015 3:55:11 PM org.apache.velocity.runtime.log.JdkLogChute log
INFO: FileResourceLoader : adding path '.'
[INFO] Parameter: earProjectName, Value: enterprise-ear
[INFO] Parameter: groupId, Value: archetype.it
[INFO] Parameter: artifactId, Value: enterprise
[INFO] Parent element not overwritten in C:\Projekte\oasp\workspaces\main\oasp4j\oasp4j-templates\oasp4j-template-server\target\test-classes\projects\enterprise\project\enterprise\enterprise-core\pom.xml
[INFO] Parent element not overwritten in C:\Projekte\oasp\workspaces\main\oasp4j\oasp4j-templates\oasp4j-template-server\target\test-classes\projects\enterprise\project\enterprise\enterprise-server\pom.xml
[INFO] project created from Archetype in dir: C:\Projekte\oasp\workspaces\main\oasp4j\oasp4j-templates\oasp4j-template-server\target\test-classes\projects\enterprise\project\enterprise
[INFO] Invoking post-archetype-generation goals: install

**Comment by nelooo** [comment]
@hohwille , can you tell me how to reproduce the error?

I tryed to reproduce from master and develop in the oasp repo and in the fork with my feature branch without exit.

I execute the command mvn install over oasp4j project and all tests in oasp4j-templates succed. I get an error in the oasp4j-sample-core:

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] oasp4j ............................................ SUCCESS [0.734s]
[INFO] oasp4j-bom ........................................ SUCCESS [0.030s]
[INFO] oasp4j-modules .................................... SUCCESS [0.022s]
[INFO] oasp4j-test ....................................... SUCCESS [2.128s]
[INFO] oasp4j-logging .................................... SUCCESS [0.482s]
[INFO] oasp4j-configuration .............................. SUCCESS [0.117s]
[INFO] oasp4j-beanmapping ................................ SUCCESS [0.237s]
[INFO] oasp4j-rest ....................................... SUCCESS [2.512s]
[INFO] oasp4j-security ................................... SUCCESS [2.110s]
[INFO] oasp4j-jpa ........................................ SUCCESS [4.401s]
[INFO] oasp4j-jpa-envers ................................. SUCCESS [0.213s]
[INFO] oasp4j-web ........................................ SUCCESS [0.198s]
[INFO] oasp4j-templates .................................. SUCCESS [0.013s]
[INFO] oasp4j-template-server ............................ SUCCESS [33.915s]
[INFO] oasp4j-samples .................................... SUCCESS [0.011s]
[INFO] oasp4j-sample-core ................................ FAILURE [15.597s]
[INFO] oasp4j-sample-server .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

**Comment by nelooo** [comment]
I execute the mvn install over oas4j-templates without error, too:

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] oasp4j-templates .................................. SUCCESS [1.193s]
[INFO] oasp4j-template-server ............................ SUCCESS [36.356s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

This is very strange. 

Maybe I'm missing anything?

**Comment by hohwille** [comment]
Indeed strange.
> mvn -v
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:3
7+02:00)
Maven home: C:\Projekte\oasp\software\maven
Java version: 1.7.0_79, vendor: Oracle Corporation
Java home: C:\Projekte\oasp\software\java\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "x86", family: "windows"

**Comment by hohwille** [comment]
I created a fresh clone and have the same error.
Perhaps a third one should give it a try and let us know.
I hate these ugly situations where errors are not reproducible.

**Comment by amarinso** [comment]
I've tried on several Linux versions that I have and no errors.

What repo/branch are you cloning exactly?

**Comment by nelooo** [comment]
I found the problem, is due of maven version.

I was using maven 3.1 (probably same of @amarinso). I upgrade to maven 3.2 and I reproduced the problem.

Now I will try to solve it.

**Comment by amarinso** [comment]
@nelooo I'm using  the  same  version  of  maven  as @hohwille

**Comment by nelooo** [comment]
That's true @amarinso, I reproduced the error due to a miss configuraion in maven 3.2.

After configuring maven 3.2 correctly I complete the mvn install.

I use maven 3.3.3 and I complete mvn install, so it's not due of maven version.

My conclusion was a mistake, I will further investigate in order to reproduce the error.

The other diff I found was de O.S. @amarinso and me use Unix systems and @hohwille use Windows. Maybe this is the way to reproduce the error.

> mvn -v
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: /home/npuchade/work/java/apache-maven-3.3.3
Java version: 1.7.0_45, vendor: Oracle Corporation
Java home: /home/npuchade/work/java/jdk1.7.0_45/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.8.0-44-generic", arch: "amd64", family: "unix"


---
> mvn install
...
[INFO] Reactor Summary:
[INFO] 
[INFO] oasp4j-templates ................................... SUCCESS [  0.827 s]
[INFO] oasp4j-template-server ............................. SUCCESS [ 29.778 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

**Comment by hohwille** [comment]
> The other diff I found was de O.S.

That would explain why there is no issue in travis or jenkins.

**Comment by dsanche2** [comment]
I have tried it in Windows 7 and it worked for me. That is my configuration:

> mvn -v
Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-11T22:58:1
0+02:00)
Maven home: C:\oasp\software\maven
Java version: 1.7.0_67, vendor: Oracle Corporation
Java home: C:\oasp\software\java\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "x86", family: "windows"

**Comment by hohwille** [comment]
Jep. I can confirm that it works for me on windows with maven 3.2 (at least 3.2.3 and 3.2.5) but fails with 3.3 (at least 3.3.3). That is really crude... We should file a bug in maven. Probably not so easy to isolate the problem...

**Comment by hohwille** [comment]
Marked as invalid as this is not an OASP bug but a maven bug. But leaving open until further clarified.

**Comment by may-bee** [comment]
maybe related to this https://issues.apache.org/jira/browse/MNG-5809 ?

**Comment by hohwille** [comment]
> maybe related to this https://issues.apache.org/jira/browse/MNG-5809 ?

jep, looks like thats it.

**Comment by RalfBayer** [comment]
The workaround provided in the Maven bug report helped for me.

**Comment by hohwille** [comment]
@RalfBayer thanks for confirming. I also used this trick meanwhile. Still it is sad that maven does not solve the problem directly...
I will close - no issue of OASP.

**Comment by ugultopu** [comment]
For the record, I am copying the trick provided in the [Maven bug report](https://issues.apache.org/jira/browse/ARCHETYPE-488) to here:

    cd %MAVEN_HOME%\bin
    mklink mvn.bat mvn.cmd

This fixed the problem for me.

**Comment by hohwille** [comment]
We can upgrade archetype to `3.0.1` to get rid of this problem without workaround forever.

**Comment by hohwille** [comment]
Fixed by proper merging of branches and PRs that have already been integrated:
https://github.com/oasp/oasp4j/blob/a858d6556cafd30f7226e7928f71549b29b74107/pom.xml#L38
