### ISSUE TITLE
insufficient permission distinction for UcManageTableImpl#saveTable

### ISSUE THREAD

**Issue by may-bee** [oasp/oasp4j#240]
Currenlty, we just have the PermissionConstant `SAVE_TABLE` for creating and updating tables.
I think this is not enough as we have to distinguish between chief and waiter actions. The chief should be able to create new tables for his restaurant. Nevertheless, the waiter may should not!? The waiter should only be able to change e.g. the  state of a table.

What do you think? Should we distinguish this?

**Comment by hohwille** [comment]
We decided in General to use ```SAVE_*``` for create and update. Only when there is specific need we will additionally create a ```CREATE_*``` permission and distinguish/separate.
So far we did KISS. If you need the use-case to separate this go for it. I currently do not see a problem but from a more command and conquer driven chief you may be correct.

**Comment by may-bee** [comment]
Ok thanks for clarification. I will discuss this issue with the students for their mobile applications. As this is just a sample application there is no real need for that, but maybe it allows to distinguish the roles a little bit more clearer.
