### ISSUE TITLE
Unnecessary extension of AbstractBeanMapperSupport

### ISSUE THREAD

**Issue by dsanche2** [oasp/oasp4j#250]
I noticed in XXXmanagementImpl classes, we extend AbstractBeanMapperSupport class but, by inheritance,  we already extend AbstractBeanMapperSupport. UCFindXXXImpl and UCManageXXXImpl extend AbstractTableUc and this class extends AbstractBeanMapperSupport, so it is redundant.

**Comment by hohwille** [comment]
Thanks for your suggestion and feedback.
Well, the extension of ```AbstractBeanMapperSupport``` for the different class hierarchies of ```XXXmanagementImpl``` and ```UcXXXImpl``` are pretty much independent. The facade (```XXXmanagementImpl```) currently only does stupid delegation. However in a real and big application that might not be true. There can be additional need for providing higher level Use-Case compositions. Still one could argue that this could also go to a use-case. However it does not really matter if ```XXXmanagementImpl``` inherits from ```Object``` or from ```AbstractBeanMapperSupport```. But in case someone wants to access the bean mapper from some reason it is already there. As we are doing code-generation and want to have a very clear pattern we decided for this approach.

As we have ```AbstractUc``` that derives from ```AbstractBeanMapperSupport``` we can introduce ```AbstractComponentFacadeImpl``` (that currently only derives from Object but can be changed to extend ```AbstractBeanMapperSupport``` or whatever a project may need) and derive all ```XXXmanagementImpl``` classes from and change the cobigen templates accordingly. This gives the best freedom and flexibility.

**Comment by hohwille** [comment]
So we are done here... Thanks for the PR @dsanche2 and thanks for adapting templates @lgoerlach
