### ISSUE TITLE
code-style: omitt @inheritDoc use @Override also for interface methods

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j#251]
We should update our code-style to remove the pointless javadoc snipplets:
```
/*
 * {@inhertiDoc}
 */
@Override
public void myMethod() { ... }
```

This JavaDoc is a pointless waste of 3 lines in source code and we have this for each method that sums up quite a lot. This @inheritDoc stuff is however legacy and outdated. If we have @Override we already have all we need and javadoc gets inherited already. This works with IDE support for JavaDoc als well as with the JavaDoc tool itself.

So first we should change the settings in oasp4j-ide and then we should automatically remove all the "empty" @inheritDoc JavaDoc blocks.

**Comment by hohwille** [comment]
Also ```{@code null}``` is more compact than ```<code>null</code>``` (same applies for true and false).

**Comment by hohwille** [comment]
IDE settings have been updated. New code should be created without.
We only need some cleanup here. Might be done with notepad++ and find in files within a short time. Somebody available?

**Comment by dsanche2** [comment]
I will do it.

**Comment by lgoerlach** [comment]
Great! CobiGen templates are cleaned up now, too.

**Comment by hohwille** [comment]
All done now.
