### ISSUE TITLE
java.version property overriden by JRE version in resource filtering

### ISSUE THREAD

**Issue by sobkowiak** [oasp/oasp4j#263]
Comments in #255 describe a problem with `java.version` variable overrided by JRE version while filtering the archetype resources.

**Comment by sobkowiak** [comment]
As a workaround we can introduce a temporary variable `template.java.version` in tempate pom initialized with the value `java.version` defined in the main pom. We can next use the temporary variable in filtering in the archetype resources. We should next try to check where is the real problem. 

I have started maven build with the debug mode and I can see the variable `java.version` defined in pom is overriden later by the JRE version while filtering.

**Comment by hohwille** [comment]
@sobkowiak Thanks for all your work and filing this issue.
This is low priority and IMHO a maven bug. The easiest way will be to wait till we extend from spring boot POM and then we have ```${java.version}``` out of our pom and just set ```<java.version>1.7</java.version>``` or more likely ```<java.version>1.8</java.version>```.

**Comment by amarinso** [comment]
By the way, I've not found our baseline version for OASP but on the pom.

Are we aiming to be compatible for <1.7 or has to be >=1.7

We should make this clear on some documentation (platform guide, tutorial or on the website)

**Comment by hohwille** [comment]
We are not supporting java below 1.7 anymore. As 1.6 is already out of lifecycle and totally unmaintained (serious unpatches security issues) this should not be an issue.
However, we intentionally avoided java 1.8 code yet to still support 1.7 for a longer while.

**Comment by hohwille** [comment]
However, the app template (archetype) is for new projects. If someone starts a new java project today it would be crazy to start with 1.7 except it is a large company that is making very strong IT governanace rules (e.g. some bank) and they can manually change the property to 1.7 if they like.

**Comment by amarinso** [comment]
Well, some of our clients are still using old application servers and don't have plans to move forward anytime soon.

To guarantee that we comply with 1.7 I think that we should stay with this so the jenkins builds check we don't introduce new features by mistake.

**Comment by hohwille** [comment]
@amarinso I am totally with you but I just want to say that the archetype (at least from oasp 2.0.0 on) should be provided with 1.8 as default.
