### ISSUE TITLE
dealing with tx (@Transactional)

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j#264]
1. We need to have ```@Transactional(value=TxType.REQUIRED)``` (resp. ```Transactional(propagation=Propagation.REQUIRED)```) on our Component-Facade-Impl (reps. Use-Case-Impl as well?).
2. There was an open discussion via mail to remove @Transactional from services (that I would not recommend) but that has to be clarified.

**Comment by hohwille** [comment]
Within this issue we could also address to consistently move to the JEE standard annotation @Transactional and remove spring proprietary one.

**Comment by amarinso** [comment]
> There was an open discussion via mail ....

Can we have more info here to get insight of that conversation?

One problem that I see with annotating the service is that in order to break the transaction you have to throw an exception that goes to the client. (Or you can access the transaction context and perform a programmatic `setRollbackOnly`) 

So for fine grain transaction management maybe is better to start them on the logic layer.

Other border case in which shouldn't be necessary is when the service is a WS with JMS transport. Here the framework (CXF/or application server) already starts the transaction with the JMS infrastructure in order to manage the commit/rollback of the processed message to the queue.

**Comment by hohwille** [comment]
> One problem that I see with annotating the service is that in order to break the transaction you have to throw an exception that goes to the client.

Such exception is still intercepted (for REST by ```RestServiceExceptionFacade```). To cause a rollback it is the proper pattern to throw an exception. Accessing TX context and calling ```setRollbackOnly``` should IMHO be avoided.
If we actually use AOP and annotations as currently proposed by OASP I see no other way to do it anyways. With Java8 and lambdas one could get rid of the AOP and annotation stuff and get more control with yet easy maintenance. However, this is not the case in the next future for us.

Other case: If a TX is already in place then the additional annotation and according aspect will not interfere (except we would explicitly configure it this way, what is not planned).

**Comment by maihacke** [comment]
As I started the discussion via mail with Jörg:
In more complex applications you will need different propagation levels per use case. So I think it is easier to have the annotations in the logic layer. In simple cases there is no difference between the proposed model and the current one. But if thinks get more complex and you started with annotations at the service levels and then have to annotate some uses cases, the annotations get cluttered through you application.

**Comment by amarinso** [comment]
When looking around for arguments for this issue I came to this response on StackOverflow that exactly explains my thoughts, mainly about separation of concerns for each layer.

Keep into account that what they mean for "service layer" is indeed our "logic layer".

http://stackoverflow.com/questions/23118789/spring-mvc-controller-shouldnt-be-transactional-why

@hohwille I'm also not in favor of calling `setRollbackOnly`. So for me the pattern to use will be to delegate all transactional management to the logic layer. If you rollback the transaction there by throwing an exception you can catch it on the service layer and return something meaningful without relying on the exception facade.

**Comment by hohwille** [comment]
So we all agree to have @Transactional on our logic layer (universal place would be component facade impl what is then in-depended of pattern used).
Remaining question is:
* Which @Transactional annotation shall we use? (according to OASP philosophy JEE annotation should be preferred).
* Shall we keep @Transactional on services? (IMHO yes, but feel free to bring arguments against it).

**Comment by amarinso** [comment]
If Spring is compatible with Java EE annotation we should go with the standard.

I'm in favor of having the transactional concern only on the logic layer. Services should only be an interface for external access and should not know how the internal behavior works. In fact this is what is explained on the link I attached with better words than mine.

So, removing `@transactional` from services for me.

In Java EE the transaction is automatically started when entering an EJB even without the annotation. In order to have the service layer starting the transaction it should also become an EJB. Not that is inherently wrong but most of the time unnecessary.

**Comment by hohwille** [comment]
Agreed. If someone needs a complex service operation calling multiple use-cases he can still add @Transactional to that method (so it should not be forbidden to do so) but we will remove such from our sample app.

**Comment by hohwille** [comment]
One experience form what happens with newbie developers:
I reviewed serveral places where the service operation invoked serveral use-cases in a row. E.g. for the deletion of X first we run a verification that the deleted object is not referenced somewhere, then we delete all child-entities of X (X has a one to many relation on them), finally X is deleted.
Now the naive developer invoked 3 different UC operations that may exist on purpose but did not realize that he now runs this in 3 transactions. This is not only a performance problem but also a problem that if only the third transaction fails the user ends up in an "inconsistent" or at least undesired state as only the last TX is rolled back. Obviously one should create a combined UC operation for that and avoid coding logic into the service but I just want to state here what will happen in reality if you have developers less experienced that the once involved into theses discussions here...

**Comment by maihacke** [comment]
I can't understand why those uses cases are called individually from the service layer. If it is necessary to verify that there are no references before deletion, this verification should be done in the delete use case. I think it is bad style to provide a "unsafe" use case which deletes entries without appropriate validation.

**Comment by ksola** [comment]
The transactional annotation are moved to the Logic Layer. I think that the wiki page should also be updated: https://github.com/oasp/oasp4j/wiki/guide-service-layer . There is written that the service Layer should be responsible for transaction handling.

**Comment by amarinso** [comment]
Ok, changed both on:

https://github.com/oasp-forge/oasp4j-wiki/wiki/guide-transactions
and
https://github.com/oasp-forge/oasp4j-wiki/wiki/guide-service-layer
