### ISSUE TITLE
JAX-RS: Auto-discovery of root resources and providers

### ISSUE THREAD

**Issue by amarinso** [oasp/oasp4j#267]
From the CXF documentation:
> Starting from CXF 3.0.0 it is possible to enable the auto-discovery of JAX-RS roots and providers with the regular CXF JAX-RS endpoint declarations done in XML 

> If you prefer doing a pure Spring-based auto-discovery you can have @Component added to JAX-RS application classes and do

```
<beans xmlns="http://www.springframework.org/schema/beans"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:jaxrs="http://cxf.apache.org/jaxrs"
      xsi:schemaLocation="
         http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-2.0.xsd
         http://cxf.apache.org/jaxrs http://cxf.apache.org/schemas/jaxrs.xsd">
 
     <import resource="classpath:META-INF/cxf/cxf.xml" />
      
     <!-- 
         Discover all root resources and providers in packages starting from "a.b.c" 
     -->
     <jaxrs:server address="/customers"/>
     <context:component-scan base-package="a.b.c"/>
 
 </beans>
```

I've tried and seems to work ok, I think is a good addition as it simplifies the configuration for the programmer and allows for an easier integration of OASP "plugins". Think of a module that provides its own JAX-RS endpoints (for example a module for monitoring) without having to add them manually to the `<jaxrs:server>` bean

**Comment by hohwille** [comment]
We already did the same via a starter class in spring boot. Thanks for your improvement for spring-classic. However, how does spring or CXF find the beans that are actually JAX-RS services? Guessing based on annotations? Is there some link we can add to the documentation?

**Comment by amarinso** [comment]
Sorry, I intended to add the link when citing the CXF source:

http://cxf.apache.org/docs/jaxrs-services-configuration.html#JAXRSServicesConfiguration-Auto-discoveryofrootresourcesandproviders

**Comment by hohwille** [comment]
We should then update here:
https://github.com/oasp-forge/oasp4j-wiki/wiki/guide-service-layer#jax-rs-configuration

**Comment by amarinso** [comment]
I take that.

also CobiGen should be updated to avoid the insertion on `beans-services.xml`. I think @dsanche2 can take that if he modifies also CobiGen for the simplification of the component facade.

**Comment by hohwille** [comment]
Is the same also supported for JAX-WS? It would be more consistent to have it the same way for both.

**Comment by hohwille** [comment]
> Sorry, I intended to add the link when citing the CXF source.

As always CXF docs are extremely poor. It does not address my question at all. Seems I have to dig in the source-code to find the answer.

**Comment by lgoerlach** [comment]
> also CobiGen should be updated to avoid the insertion on beans-services.xml. I think @dsanche2 can take that if he modifies also CobiGen for the simplification of the component facade.

I have just done that. The latest templates can be pushed to the repository soon (as Malte has started working on the issue preventing me from doing that).
@dsanche2: If you need them right away for working on the component facade, let me know.

**Comment by amarinso** [comment]
I've merged the PR on this issue
