### ISSUE TITLE
Configuration of filters (CSRF, CORS)

### ISSUE THREAD

**Issue by amarinso** [oasp/oasp4j#278]
We are about to add another filter to the sample application (PR #274). Reviewing the Csrf filter configuration it is using `#{systemProperties['CsrfDisabled']}` which I think is a bit confusing because configuration should be primary on property files.

My proposal is to change this to use a property and one with "positive logic", that is, instead of writing "disableSomeFilter" make it "enableSomeFilter" and playing with default values.

for example we could have by default:

```
oasp.filter.csrf=true
oasp.filter.cors=false
```

and on the spring context file we use `${oasp.filter.csrf}`

In order to do this, we have to move the definition of the properties up on the context definition because if not I couldn't use the placeholder before loading beans-common.xml. I've made a PR #277 for this also.

**Comment by may-bee** [comment]
`oasp.filter.cors=false` as default is fine for me.
Thus, we will not change the currently deployed behavior of the application and we can simply try, whether our OASP4Mobile approach works against the cors configuration.
