### ISSUE TITLE
Change Spring context includes to separate concerns

### ISSUE THREAD

**Issue by amarinso** [oasp/oasp4j#281]
Reviewing the sample application for the #278 (CORS filter) I came to this tree of spring/context xml file dependencies/inclusions

![oasp4j context order](https://cloud.githubusercontent.com/assets/9352103/8520551/85656880-23db-11e5-8987-4bcfe250b74e.png)

Here I think beans-services is taking too much responsibility and also we have common beans loaded by dataaccess context.

I would rather separate this to match this other picture:

![oasp4j context order proposal](https://cloud.githubusercontent.com/assets/9352103/8520573/b277c6b0-23db-11e5-9eb4-b335cd376c72.png)

I've already issued a PR #280 in order to address this.

**Comment by hohwille** [comment]
Can you give more motivation? If I want to test services I now only need to load beans-services and all dependent beans are resolved via include. If I only want to test logic without services, I just load beans-logic instead and further if I only want to test a DAO, I only need to load beans-dataaccess.
That pretty much matches our layered architecture.
What does not match the picture for me is that websocket-context.xml should also be in service folder and not in separate websocket folder and should follow our naming conventions (the websocket stuff has never been reviewed als is still missing javadoc, etc.).

But what is the motivation for your general redesign?

Be also aware that we are planning to go for spring boot (issue #232) what will make all these XMLs obsolete. So why this redesign that may cause problems, irritation, etc.?

**Comment by amarinso** [comment]
My motivation was driven by reviewing the sample application logic without realizing about the test.

For example, having a context called `beans-commons` and have it loaded by the `beans-dataaccess` doesn't seem logical to me. If it is says common in its name it suggests to be the place to put beans shared through the application, related to all layers.

The other change was to extract the `beans-logic` from the `beans-service`. I recon that it's difficult to have a web application with logic not published with a service layer but having it separated seemed more logical to me... first instantiate the logic, then wrap with service layer... and while writing this I realize that may lead to extract also the dataaccess prior to defining the logic....

So the `beans-applications` should contain the following in order:

- beans-common
- beans-dataacess
- beans-logic
- beans-services

On the other side, having Spring Boot will get rid of the context files but I suppose that it will bring also some kind of ordering for what to scan/include/instantiate... so maybe the discussion is also valid for this case.

In either case I think that we should properly document why are we organizing the code the way it is. Your comment about the tests using the right context file is spot-on.

Does any of this make sense or do we leave it as it is?

**Comment by amarinso** [comment]
On second (or third) thought I think the current ordering is convenient and we should only add the logic behind it to the documentation. It was cumbersome to get the whole picture of the dependencies by following the imports.

But I still think that we should move at least the `propertyConfigurer` bean from `beans-common` up on the order because that way we can make use of properties on other places, like on filters. Issue #278 was my motivation behind this quest.

**Comment by amarinso** [comment]
Added the pic to the documentation.
