### ISSUE TITLE
documentation: Use of JAX-RS Rest client

### ISSUE THREAD

**Issue by amarinso** [oasp/oasp4j#287]
We should include an example and recommendation to use REST client API

copied from [jersey](https://jersey.java.net/documentation/latest/client.html) page 

> JAX-RS Client API, which is a fluent Java based API for communication with RESTful Web services. This standard API that is also part of Java EE 7 is designed to make it very easy to consume a Web service exposed via HTTP protocol and enables developers to concisely and efficiently implement portable client-side solutions that leverage existing and well established client-side HTTP connector implementations.

**Comment by hohwille** [comment]
We have this in tests. Documentation could link a test-case.
However, we need support for accessing own services in the app landscape with JAR-RS as we need to pass correlation ID, etc. So there is actually some missing piece here.

**Comment by hohwille** [comment]
Done long time ago
https://github.com/oasp/oasp4j/wiki/guide-service-client
