### ISSUE TITLE
improve logging config (modularization/reuse)

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j#290]
I just found this one:
https://github.com/ulisesbocchio/jasypt-spring-boot/issues/3

```
<configuration>
    <include resource="org/springframework/boot/logging/logback/base.xml"/>
    <logger name="org.springframework.context.annotation.ConfigurationClassEnhancer" level="ERROR"/>
</configuration>
```

We should also provide an OASP conform base configuration for logback that can be extended this way and comes with oasp4j-logging.

**Comment by amarinso** [comment]
I thought that we were against providing this base "objects" on the framework and giving the most to the application.

We have to question the dis/advantages of this approach (also on other topics):

By having it on the framework:
- It is easier when upgrading the base version
- If everything is provided by the framework it is easier for the project. It has less to take care, there are less archives involved.
- In this case a `logback.xml` file is still needed
- It is more inconvenient to look at the contents of the file for extension/modification
- There maybe things that could not be deleted/overrided

I see some positive points and some negative, but maybe it's more important to keep coherent decisions. If we do this we could include some classes/files from the sample application on the framework modules.

Also I think it is a matter of having better documented the sample application/archetype

**Comment by hohwille** [comment]
IMHO you did not understand my suggestion. I do not want to provide ```logback.xml``` but I want to provide as base configuration. We are defining a standard and have documentation that tells others what to write in their logback.xml to follow this standard. What I wrote is a beautiful way to solve this with a simple include. People are free to used it avoiding redundance (we currently already have this redundancy in our OASP) or to ignore it.

**Comment by hohwille** [comment]
My point of view:
Logger configuration consists of various aspects:
* Layout (how a logline is formatted)
* Appending (where the loglines are written to)
* Loggers and their levels (which log messages to suppress and which should go to which logger)
* etc.

All this is mixed in one file. As we define a standard for the first, a suggestion for the second and leave everything open for the last, my suggestion will make sense and everybody is still free to "override" by just not importing the standard. But then he does not follow the standard.

**Comment by amarinso** [comment]
@hohwille I've made a PR #293 please check if this is what you where trying to achieve

I've also extracted some properties from `logback.xml`
- `appname` (had a reference to restaurant)
- `log.pattern`

**Comment by hohwille** [comment]
Please have a look at my updated PR that I created as fork from yours.
Documentation update will not be done before we agreed and merged.

**Comment by hohwille** [comment]
BTW: My PR is #314

**Comment by hohwille** [comment]
Also I would question if hourly rotation is really better than daily rotation as default.
We took this from RF but I am not sure if this is the best choice.
At least therefore I designed the properties in way that this can be changed easily by overriding properties without touching appenders.

**Comment by MarcoRose** [comment]
PR #314 has been merged. Done.
