### ISSUE TITLE
Security, sample application: Missing function level access control

### ISSUE THREAD

**Issue by marpuch** [oasp/oasp4j#292]
Being logged in as a waiter I was able to run the cooks functions. There is an issue in the application with respecting roles permissions to run functions.

![untitled session - test - owasp zap 2 4 0_2015-07-11_23-33-58](https://cloud.githubusercontent.com/assets/797670/8736122/23d2e47e-2c16-11e5-856f-eeb3d9493456.png)

**Comment by julianmetzler** [comment]
According to the [access-control-schema.xml](https://github.com/oasp/oasp4j/blob/develop/oasp4j-samples/oasp4j-sample-core/src/main/resources/config/app/security/access-control-schema.xml) the waiter role inherits rights from barkeeper and the barkeeper inherits from cock so the behavior seems valid to me.

**Comment by marpuch** [comment]
If it's part of the spec, then it's ok. I'll try to test it the other way around next time. The ticket can be closed.

**Comment by hohwille** [comment]
IMHO this is not a violation of OWASP#10 but we still have to revisit this from a business point of view (due to lack of full specification, yet). It is correct that waiter inherits from barkeeper. However, why does barkeeper inherit from cook? That one needs to be revisited and IMHO it is wrong and @marpuch was confused by this on purpose.

**Comment by hohwille** [comment]
A simple example: The cook can mark a meal as prepared. Why should a waiter be allowed to do this also? In the domain of a restaurant this is all not critical and it might be often be even more convenient to allow the employees of the restaurant more than they need for their daily business so in some extra-ordinary situation the process does not get stuck. However, if we use that restaurant also as a show-case for IT-Security we get a different point of view and that is how @marpuch is looking at it.

To summarize I would say that we have a showcase to demonstrate many features of the OASP and the challenges of software engineering. So we should be strict about IT security here as if it was a domain with higher demands in this area. In general @marpuch is correct that you should not be able to do things via REST that you can not also do via the UI (except the UI is incomplete and there is just some feature currently not yet implemented).

As a first step, I will create a new issue to revisit the permissions from a business perspective.
