### ISSUE TITLE
oasp ide setup: last step of 10.iii) does not work

### ISSUE THREAD

**Issue by maximilianemanuel** [oasp/oasp4j#299]
I wanted to get started with oasp, and tried out the oasp environment from the local file system how descriped in the wiki. Everything worked except the last step of 10.iii) when I tried "mvn install", following exception was thrown:
````
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.3.1:exec (n pm) on project oasp4js-sample: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
````

I modifed the pom.xml, so no jsclient was produced anymore, the rest worked. Afterwards I tried to fix it again, but now I'm getting another error when executing the command: ````npm install -g bower```` (EPEERINVALID):
````
npm ERR! peerinvalid The package karma does not satisfy its siblings' peerDepend encies requirements!
````

**Comment by hohwille** [comment]
If even this command does not work:
> npm install -g bower 

Then there is some general error and your node.js / NPM installation is not sane.
If you go to jsclient app direcotry and just run this:
> npm install

Do you also get an error? Or does this work?

**Comment by hohwille** [comment]
Did you ensure to run such commands from a properly initialized shell (```console.bat```, ```Open CMD here```, or from Eclipse Terminals View)?

**Comment by maximilianemanuel** [comment]
I tried out running the commands from a properly initialized shell `console.bat`

But what I wanted to mention: initially, `oasp4js/java/target/oasp4js-sample-*-web.zip` could not be produced, I had to edit the file `pom.xml`, because of following error on executing `mvn install`:
````[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.3.1:exec````

yes, running `npm install` will also fail:
````
npm ERR! peerinvalid The package karma does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer gulp-karma@0.0.4 wants karma@>=0.10 <=0.13
npm ERR! peerinvalid Peer karma-coverage@0.2.6 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-junit-reporter@0.2.2 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-phantomjs-launcher@0.1.4 wants karma@>=0.9

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Users\\mschuele\\oasp_v4\\software\\nodejs\\\\node.exe" "C:\\Users\\mschuele\\oasp_v4\\software\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Users\mschuele\oasp_v4\workspaces\main\oasp4js
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR! code EPEERINVALID
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\mschuele\oasp_v4\workspaces\main\oasp4js\npm-debug.log
npm ERR! not ok code 0
````
but this errors first occured after several approaches (so I'm sure, it was my fault...)

**Comment by maximilianemanuel** [comment]
afterwards, I checked out the projects in a new folder and configured the environment variables manually, that worked, but I was a bit sad not to know what I did wrong

**Comment by may-bee** [comment]
Please check again. We have changed some dependencies in the oasp4js repository, which may fix this issue.

**Comment by hohwille** [comment]
No bug seems to be left. This issue is misplaced here anyhow. If you have further trouble with npm and oasp4js go to https://github.com/oasp/oasp4js/issues.
