### ISSUE TITLE
configuration infrastructure

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j#3]
we need some configuration module. I already created it as empty with just a constant with the spring standardized configs for reference in unit tests. The config module should at least address:
1. Access configurations (from properties files)
2. Read and Write single attributes
3. Support for reloadable configurations

Maybe something to look at:
http://www.morgan-design.com/2012/08/reloadable-application-properties-with.html

**Comment by MarcoRose** [comment]
This will be resolved with introducing spring boot #232. Closing this.
