### ISSUE TITLE
JPA: Stop "renaming" entities for queries

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j#300]
We are using the suffix Entity for all JPA-Entities in OASP. As we do not want to have this in the Table name and also to keep that table name stable on refactorings we annotate the table name with ```@Table``` annotation. That is fine and makes sense. However, we also do the same for the entity name so the name in queries is also changed. This turned out to cause more confusion for developers as being helpful:
```
@Entity(name = "Banana")
@Table(name = "Banana")
public class BananaEntity extends ApplicationPersistenceEntity { ... }
```

So if a developer writes a query and knows the class name is "BananaEntity" he has to use "Banana" in his queries. We should remove the Entity name Attribute (also from CobiGen Templates) so it is just ```@Entity```.

Any concerns or agreement?

**Comment by hohwille** [comment]
If someone later on does a refacotring and renamed BananaEntity to FruitEntity and he does not want to modify the queries he can still add the name attribute manually and set it to "BananaEntity" so queries remain working. As this can also cause even more confusion it should not be considered best practice.

BTW: When using QueryDSL you never have to worry about this as you reference the entity as class literal and do not use the name string.

**Comment by maihacke** [comment]
I agree, let's remove @Entity. Renaming entities does not occur to often, and when find/replace in named queries should be easy...

**Comment by hohwille** [comment]
PR with fix has been merged. CobiGen is out of scope for OASP. File a separate issue there.
