### ISSUE TITLE
Rethink getProductPicture service of return type multipart 

### ISSUE THREAD

**Issue by maybeec** [oasp/oasp4j#304]
In the latest project, we observed, that processing multipart bodies is not a often used pattern.
We should consider streaming the binary and transmitting necessary metadata via headers. If there are additional meta data, we can provide an additional service allowing to retrieve more information seperately to the binary data.

**Comment by hohwille** [comment]
Restaurant sample app has been deleted. If such bug exists for MTS, we have to file it there.
