### ISSUE TITLE
Upgrade to Apache CXF 3.1.x

### ISSUE THREAD

**Issue by sobkowiak** [oasp/oasp4j#306]
The new branch `3.1.x` is now stable and we should consider upgrade to this branch. 

See [Migration guide](http://cxf.apache.org/docs/31-migration-guide.html) for more details

**Comment by sobkowiak** [comment]
Release notes for the last version: http://cxf.apache.org/cxf-313-release-notes.html

**Comment by MarcoRose** [comment]
Please indicate the impact for projects that upgrade to cxf-313 and for the restaurant example. 
Please comment on the need for full regression testing for the restaurant example.

If you consider this a change with little impact, this ticket can be done asap.
If this is a change that requires a software-migration, this ticket needs to wait.

**Comment by sobkowiak** [comment]
Because we plan to release next the new major version (2.0.0) it's a good idea to perform the upgrade now. There should be no problem for existing applications, because CXF works also in OSGi environment and according to the [semantic versioning](http://semver.org/) the new minor version (in this case 3.0.x -> 3.1.x) should introduce no breaking changes from the client perspective. No migration should be required.  I'll prepare the pull request and merge it if the travis build is ok.

**Comment by sobkowiak** [comment]
I have prepared a pull request which upgrades to 3.1.3. It's tested and I have found no issues. As mentioned in previous comment this version is backward compatible with CXF 3.0.x.
