### ISSUE TITLE
CSRF token in GET requests not respected

### ISSUE THREAD

**Issue by atulejko** [oasp/oasp4j#311]
The CSRF token is attached to GET requests, but is not validated. Since all the state-changing requests are sent as POST requests and not GET requests, it is not an issue at the moment. 
If any state-changing requests would be become GET requests at any point, we would have then the security issue. 

Additionally, attaching the CSRF token to GET requests without validating it, is probably not what was originally designed.

**Comment by marpuch** [comment]
Just to put an example about how the GET requests in the sample application look like:

    GET http://oasp-ci.cloudapp.net/oasp4j-sample/services/rest/offermanagement/v1/product HTTP/1.1
    User-Agent: Mozilla/5.0 (Windows NT 6.1; rv:37.0) Gecko/20100101 Firefox/37.0
    Accept: application/json, text/plain, */*
    Accept-Language: en-US,en;q=0.5
    X-CSRF-TOKEN: 47ac2d70-37d5-40b4-a1eb-4ee15ebd242c
    Referer: http://oasp-ci.cloudapp.net/oasp4j-sample/jsclient/
    Cookie: JSESSIONID=5BC7170F105BC6982CFE7FCB916D4778
    Connection: keep-alive
    Host: oasp-ci.cloudapp.net

The passing of the X-CSRF-TOKEN could be omitted and the request would still work. This is a bit surprising and created an uneasy feeling about the provided solution at first glance. Still this is the default behavior of the springs `org.springframework.security.web.csrf.CsrfFilter` filter where „The default is to apply CSRF protection for any HTTP method other than GET, HEAD, TRACE, OPTIONS.”

How to tackle the problem? I see following solutions:
1. Update the client side of the sample application not to attach the CSRF token to GET requests (no confusion for the developers). Make sure the developers understand that no GET request is CSRF protected.
2. Force CSRF token protection for all requests (GET included). This is a nice secure default, it just makes life harder for developers.

I would probably go for 1.

**Comment by hohwille** [comment]
This is the standard approach of spring-security and sending the CSRF-Token in every request is just plain KISS. I personally do not see a problem at all here.
However, if required for some reason 1. would be the way to go.
IMHO only unnecessary complexity.

**Comment by hohwille** [comment]
FYI: If 1. should be done then we would need a issue ticket in oasp4js and not here.
To complete this ticket we could do one improvement:
* Explain this in the documentation and add a note that GET requests must NEVER trigger a modification but only retrieve data without chaning state (esp. in persistent stores).

**Comment by marpuch** [comment]
I'm ok with 1. 

@atulejko already created an issue in oasp4js (https://github.com/oasp/oasp4js/issues/75). Thank you.

It would be nice to have this one thing documented for the developers information.

**Comment by amarinso** [comment]
I've have a doubt when audited entities are accessed.... The information about who/when accessed maybe is modified. 

In this scenario... Is still GET considered as read-only? Or should this entities be queried through POST requests?

If CSRF is no issued on GET there is a chance for an attacker to fool the auditing system and this can be a problem if some regulations must be enforced.

**Comment by hohwille** [comment]
Creating GET requests that actually mutate the state (change something in the Database) is totally sick and evil. If you do so you have a really big flaw.
The Idea of REST is that it is easy to use - even for humans. Requiring CSRF-Token for GET requests is rendering this benefit void. It will be a big pain for developers.

I do not see why it is a problem to ignore CSRF-Token for GET.
This is IMHO just common sense on the web.

**Comment by hohwille** [comment]
> I've have a doubt when audited entities are accessed.... The information about who/when accessed maybe is modified. 

Maybe I just do not understand, what you mean with this? Reading the history (audit) is a read only operation. The access is restricted by authorization.

> In this scenario... Is still GET considered as read-only? Or should this entities be queried through POST requests?

Can you make your point clear.

**Comment by hohwille** [comment]
To make my point clear:
We agreed that we do not want to go for 2.
I want to close this issue as wontfix/invalid.
If someone wants to go for 1. then create a new issue in oasp4js.

**Comment by amarinso** [comment]
Maybe I am miss-using the term "audited" for consulting entities that have to save "accessed time" and "accesed user" when retrieved. I was thinking on some legal notification that has to be marked as "read" when accessed.

I was thinking that the easiest way to access is this information retrieving that entity by GET... but that way it will be "sick and evil" and it should be accessed by POST.

In our old framework we had this functionality on entities and called "auditing" to that functionality, hence my confusion... but also we are using POST for everything so... we where not totally evil :-)

**Comment by hohwille** [comment]
@amarinso: Thanks for clarification. Now I understand. I was confused as the term auditing is used by envers that we are using in OASP.

In this case I would state that we are providing good defaults for the 80% case. If you have something sepcial in your project, you need to adopt. So for such demand you can consider if the auditing is acutally a modification (you may "only" log the audit trail) or not. Then you might decide to not use GET at all or to require CSRF even for GETs (what I would not recommend). There can be a documented alternative for this case with a recommended best practice. But this is totally out of scope for this issue.

**Comment by hohwille** [comment]
Issue for OASP4JS has been filed:
https://github.com/oasp/oasp4js/issues/75

There is nothing left to do here.
