### ISSUE TITLE
Consolidate Service REST Service

### ISSUE THREAD

**Issue by maybeec** [oasp/oasp4j#335]
Consolidate REST Service declarations.

Examples in `OffermanagementRestServiceImpl` (please check every REST service for this ticket
- [ ] getOffer(id) vs findProduct(id)
- [ ] `findProductByRevision` should be `getProduct`
- remove deprecated methods, which are not used anymore
  - [ ] especially remove `@Put` operations
- [ ] SalesManagement
- [ ] TableManagement
- [ ] StaffManagement

**Comment by hohwille** [comment]
Restaurant sample has been deleted. Help improving MTS instead.
