### ISSUE TITLE
Rename StaffMember#name

### ISSUE THREAD

**Issue by maybeec** [oasp/oasp4j#336]
Due to readability reasons, we should rename the `StaffMember#name` attribute to `login` as it is already persisted to the database.
Just `name` is ambiguous.

**Comment by hohwille** [comment]
Please be aware that getName() is defined by java.security.Principal.
We can not rename that method. We could only rework our security context.
Adding a transient property getLogin() additionally would duplicate the information in JSON by default.

**Comment by hohwille** [comment]
Restaurant is a dead end. IMHO solved in MTS.
