### ISSUE TITLE
Rework Payment workflow

### ISSUE THREAD

**Issue by maybeec** [oasp/oasp4j#337]
Currently it is inconvenient to do the payment:

order positions have to be payed separate to add them to a bill.
If now the payment of the bill does not work, the order positions still are in state "payed" but there does not exist a bill for it.

So it would be nice to have one global method (e.g. for the whole order) that performs the payment instead of calling multiple small methods.

**Comment by hohwille** [comment]
To say it clearly: The salesmanagement and especially billing is a real pain and has to be redesigned and reworked.

**Comment by may-bee** [comment]
:+1:

**Comment by hohwille** [comment]
Restaurant sample is dead. Help to improve MTS instead.
