### ISSUE TITLE
Negative tip possible

### ISSUE THREAD

**Issue by may-bee** [oasp/oasp4j#338]
We should at least introduce further validation to not allow negative tips in BillEtos.

**Comment by hohwille** [comment]
LOL. Nice finding. :+1: 

@NotNegativeMoney should solve this.

**Comment by may-bee** [comment]
We tested this issue today with the currently deployed version of the server and the OASP4Mobile APP on @fkreis smartphone. We could save a negative tip.
But, I have seen that the last deployment has been some time ago :) So it might be fixed by the annotation, I have also seen in the code.

**Comment by hohwille** [comment]
PR #344 has been merged. Shall we close this without a JUnit? Actually we should learn to follow red/green pattern (create test-case to prove the bug first that is red, then fix the issue in the main code, then run the test again and ensure it is green now)...

**Comment by may-bee** [comment]
I would suggest to write a test. I know that this causes additional effort for people who want to contribute, but we will not get a stable sample application otherwise, which can be already observed quite good.
