### ISSUE TITLE
Add Oder Position is possible without Order ID

### ISSUE THREAD

**Issue by may-bee** [oasp/oasp4j#339]
The OrderPosition -> Order relation should be not nullable declared in validation constraints and the database.

**Comment by hohwille** [comment]
@may-bee did you actually report a bug here? Or did you observe the code and do some guessing?
If there is a bug, please explain more or provide a JUnit to reproduce. If this is not a bug we should close.

**Comment by may-bee** [comment]
This bug has been observed from the students implementing the mobile app, which leads to some confusion and inconsistent data during development.

**Comment by hohwille** [comment]
We have added a constraint for this. Can someone confirm if this is fixed and close the issue?
