### ISSUE TITLE
Enable CXF Webservice Support for Spring-Boot

### ISSUE THREAD

**Issue by tkuzynow** [oasp/oasp4j#355]
By default SpringBoot-Application does not read configuration for CXF-Servlets from web.xml.
It's necessary to configure it in Java to be work:
```
<servlet>
    <description>Apache CXF Endpoint</description>
    <display-name>cxf</display-name>
    <servlet-name>cxf</servlet-name>
    <servlet-class>org.apache.cxf.transport.servlet.CXFServlet</servlet-class>
    <load-on-startup>1</load-on-startup>
    <async-supported>true</async-supported>
  </servlet>
  <servlet-mapping>
    <servlet-name>cxf</servlet-name>
    <url-pattern>/services/*</url-pattern>
  </servlet-mapping>
```
How to check if it works: 

The following CXF-WS service should give results:

localhost:8080/tablemanagement/v1/gettable

**Comment by hohwille** [comment]
We want to get rid of obsolete ```web.xml```.
With spring-boot we can easily create a ```@Configuration``` class that configures CXF and automatically registers all REST-Services from application context. I thought this has already been done.
@MarcoRose what is the status here?
