### ISSUE TITLE
Migrate from XML to Java-Bean-Configuration 

### ISSUE THREAD

**Issue by tkuzynow** [oasp/oasp4j#356]
Further migration of XML-Configuration to Java-Configuration is required.
Some migrations were already done (beans-jpa, some beans-services, etc.), but further work is required.

**Comment by hohwille** [comment]
What is left to do here? IMHO this is complete except for batch.
If we want to move batch config to Java as well we should create a new issue and schedule to another milestone. We can IMHO close this issue.
