### ISSUE TITLE
Start of application on external Tomcat should be enabled if Spring-Boot should be optional

### ISSUE THREAD

**Issue by tkuzynow** [oasp/oasp4j#357]
After integration with Spring-Boot and disabling of security (see https://github.com/oasp/oasp4j/issues/354) the deployment on external Tomcat stopped working (in Eclipse, via Servers->Tomcat->Start).

If Spring-Boot-launch should be only optional and some would like to start it's app with normal, Tomcat-deploy, then it should be further studied and fixed.

**Comment by hohwille** [comment]
I do not see that running it in WTP in Eclipse is really crutial. It is important that we build the app as bootified WAR and not as plain boot JAR. Further we need to test that the app works in tomcat then what should be the case.

**Comment by hohwille** [comment]
IMHO this is working. Can anyone confirm and close?
