### ISSUE TITLE
Support for JAX-RS client

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j#358]
As addressed in #287 we also need to consider calling REST-Services as a client from Java.
This is supported by JAX-RS and CXF nicely out of the box. However we need to consider different aspects:
- handling exceptions (we have defined a standard JSON format for the exception details from the server but how do we receive this from the java side? Do we need a custom implementation of `ClientResponseFilter` provided in oasp4j-rest module?)
- dealing with headers (we at least have to forward CorrelationId)

**Comment by jomora** [comment]
@hohwille, could you provide details on the JSON format for exception details? Where is it defined? Thx!

**Comment by hohwille** [comment]
https://github.com/oasp/oasp4j/wiki/guide-rest#error-results

**Comment by geoffroya** [comment]
Hi,

where is SyncServiceClientFactory.java code ?

**Comment by hohwille** [comment]
> Why did you choose to create service each time you need it, instead of injecting clients at start time?

The API allows to give individual properties (e.g. login user, timeout, etc.) that can be dynamic. Therefore the general API design is that you create a service client individually. The next question is how to actually use this. I already discussed with Angel that we should add a feature such that you can also @Inject a service API and a spring factory will then create a service client (without individual config but with general configured aspects) that can then be reused. You can also create a service client manually on component init. The usage I showed was an existing test-case that is using different logins within the same test and was already create clients on demand in each test method, hence it was natural to stay with this design.

> Where would you put circuit breaker? in UcFooImpl?

This can be done inside the async client via a SPI implementation. However, for simplicity we are proposing sidecar (https://dzone.com/articles/microservices-patterns-with-envoy-sidecar-proxy-pa) for such features.

> Why service is not in a DAO package as stated in https://github.com/oasp/oasp4j/wiki/guide-dataaccess-layer

This is still in discussion and might change. Thanks for your valuable feedback.

**Comment by hohwille** [comment]
CXF Clients seem to be thread safe:
https://stackoverflow.com/questions/13136167/are-cxf-client-proxies-thread-safe

**Comment by amarinso** [comment]
I think we should not stick to CXF clients. 

When deploying on a compliant Java EE application server usually you will want to take advantage of native web services implementation and spec says is not thread safe.

Of course if performance becomes a problem... then you could revert to a shared client pool... but that may be the edge case and not the norm

**Comment by amarinso** [comment]
@hohwille when injecting the service we could use also **prototype** scope so individual settings could apply to different client instances, no?

**Comment by hohwille** [comment]
@amarinso I am fully with you and CXF so far is just the default SPI implementation if you depend on `oasp4j-cxf-client`. Avoiding to rely on thread-safeness is also what I would prefer. Howerver, this is not as easy as you might think. You can define a spring bean as prototyp but that will only mean that whenever it is requested, a new instance is created. But if a spring bean is of type singleton and requires an instance via @Inject it will get an individual instance of that if it is scoped as prototype but that instance is then stored in a singleton and will still cause issues in case it is not thread-safe. The original spring pattern is to inject the factory then and to request the instance with each request/demand what is exactly what we already have right now. What we are aiming at is simplicity for the developer. Therefore IMHO we should require that SPI implementations provide thread-safe clients if used together with simple injection. What we can then do to make this work together with client frameworks that are not thread-safe is to create a proxy behind the service API that delegates to a `ThreadLocal` instance behind the scenes. Following kiss would mean that we currently only document all this and implement it when the first project comes that needs to use a client famework that is not thread-safe and has the need to combine all this.
Summary: This all does not affect our API design, it is just a matter of implementation and new implementations have to cope with it.

**Comment by hohwille** [comment]
Meanwhile integrated and merged. For additional features or enhancements create new and specific issues.
