### ISSUE TITLE
ProductImportJobTest fails or is unstable/indeterministic

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j#360]
https://travis-ci.org/oasp/oasp4j/builds/95341646

I am quite sure that my change is not related to the build failure. Otherwise let me know...

```
Failed tests: 

  ProductImportJobTest.testJob:57 

Expected size:<7> but was:<19> in:

<[MealEto[id=1], MealEto[id=2], MealEto[id=3], MealEto[id=4], SideDishEto[id=5], SideDishEto[id=6], SideDishEto[id=7], SideDishEto[id=8], DrinkEto[id=9], DrinkEto[id=10], DrinkEto[id=11], DrinkEto[id=12], DrinkEto[id=10000000], DrinkEto[id=10000001], DrinkEto[id=10000002], MealEto[id=10000003], MealEto[id=10000004], MealEto[id=10000005], MealEto[id=10000006]]>
```

With local maven everything works and build succeeds.

**Comment by hohwille** [comment]
When I run locally, I get only these:
```
[DrinkEto[id=10000000], DrinkEto[id=10000001], DrinkEto[id=10000002], MealEto[id=10000003], MealEto[id=10000004], MealEto[id=10000005], MealEto[id=10000006]]
```

Seems that h2 or flyway messed up something here.

**Comment by hohwille** [comment]
```
database.url = jdbc:h2:./target/.sample;INIT=create schema if not exists public
```

Why are we persisting the h2 content for testing? That is only a source of problems. We should eliminate this in entire oasp4j. Only change to local file if you have a bug that you can absolutely not track down but we should never have this published in git.

**Comment by hohwille** [comment]
I locally changed to this:

```
database.url = jdbc:h2:mem:app;INIT=create schema if not exists public
```

However the test now fails with
```
org.flywaydb.core.internal.dbsupport.FlywaySqlScriptException: 
Migration V9001_1__Delete_data.sql failed
-----------------------------------------
SQL State  : 42S02
Error Code : 42102
Message    : Table "RESTAURANTTABLE" not found; SQL statement:
DELETE FROM RESTAURANTTABLE [42102-190]
Location   : AllTests/setup/db/V9001_1__Delete_data.sql (C:\Projekte\oasp\workspaces\main\oasp4j\oasp4j-samples\oasp4j-sample-core\eclipse-target\test-classes\AllTests\setup\db\V9001_1__Delete_data.sql)
Line       : 3
Statement  : DELETE FROM RESTAURANTTABLE

	at org.flywaydb.core.internal.dbsupport.SqlScript.execute(SqlScript.java:117)
```

So also the flyway scripts are inconsistent and things are messed up.
We need to do some general rework of this.

**Comment by hohwille** [comment]
So our tests rely on side effects of previous tests.
That is rather not a best-practice...

**Comment by Ludger-Overbeck** [comment]
I had the same problem when trying to push something to module oasp4j-batch. 

I fixed it for now by deleting all offers and products from the database before executing the test itself.

Obviously there is a test case not properly cleaning up the database (the test itself does not seem to do that, too).

**Comment by jczas** [comment]
The test expects, that all needed tables exist.

In setup it prepares its data:
- cleanup tables to avoid side effects of previous tests,
- insert needed test data.

It uses flywaydb to cleanup and import test data. It is ok? Or we have another convenient concept to import test data?
