### ISSUE TITLE
Setup system and integration test

### ISSUE THREAD

**Issue by MarcoRose** [oasp/oasp4j#381]
So far no system and no integration tests are provided. These need to be added either examplery, better in full. A recent approach has been withdrawn, but is available in OASP Release 1.5.0 

https://github.com/oasp/oasp4j/releases/tag/release%2F1.5.0
module sample-server-integration

**Comment by jomora** [comment]
We introduced the test infrastructure and some showed the usage of CXF proxies and `RestTemplate` for subsystem tests.

However, it is important to use clear nomenclature here. The taxonomy available in the OASP4J wiki states that there are *system tests*. These should not be confused with *system integration tests*.
> Do not confuse a subsystem test with a system integration test. A system integration test validates the interaction of several systems where we do not recommend test automation.

Have a look at the [wiki](https://github.com/oasp/oasp4j/wiki/guide-testing#level-3-subsystem-test).

So, I think it would be possible to introduce system tests by creating a new project and executing these tests while the sample app is fully started (as we're doing it in my current engagement, this can be configured in jenkins, too). 

Nevertheless, introducing automated *system integration tests* seems not to be an option in accordance with our test taxonomony.

What do you think, @hohwille and @MarcoRose?

**Comment by hohwille** [comment]
Restaurant is a dead end. If sill relevant raise an issue for MTS. IMHO this is already on its way driven by Lukasz.
