### ISSUE TITLE
application module structure and dependencies

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j#384]
From issue #363 there are leftovers according to our module-structure.
We currently have separated an application into:
- `core`
- `server`
- `batch`

However, the server specific dependencies and launcher (Spring-Boot-Main-Class) and the batch layer code and dependencies reside in `core` that is actually a bootified JAR that the other modules depend on (what is IMHO sick).
I would propose to 
- [ ] move the server dependencies (tomcat, etc.) and according code (launcher) to `server`. 
- [ ] move the batch dependencies (spring-batch, etc.) and according code (batch layer code but not logic layer stuff for batches) to `batch`.
- [ ] make the `core` module a regular JAR (not bootified)
- [ ] make the `server` module a bootified WAR
- [ ] make the `batch` module a JAR but also provide a ZIP or TGZ as classified side-artifact.

Otherwise the entire modularization is in question and we could also just have a single module `app`. However, for reality you will need modularization. We actually would need to add a module `api` with the REST-API (JAR-RS Interface with related classes):
- [ ] create `api` module and extract Interfaces from REST-Services and move to that module.

**Comment by hohwille** [comment]
https://github.com/oasp/oasp4j/tree/develop/samples

**Comment by hohwille** [comment]
Currently `core` builds a bootified JAR and `server` builds a bootified WAR containing the bootified JAR what results in all external dependencies being duplicated. This is entirely nuts.
At least as a quickfix we need to change `core` to regular JAR packaging.

**Comment by jomora** [comment]
The following has been solved by #491:
- [x]    move the server dependencies (tomcat, etc.) and according code (launcher) to server.
- [x]    make the core module a regular JAR (not bootified)
- [x]   make the server module a bootified WAR

The following tasks are still open. 
- [ ]    move the batch dependencies (spring-batch, etc.) and according code (batch layer code but not logic layer stuff for batches) to batch.
- [ ]   make the batch module a JAR but also provide a ZIP or TGZ as classified side-artifact.
- [ ]  create api module and extract Interfaces from REST-Services and move to that module.

**Comment by hohwille** [comment]
There was some progress in this area with my-thai-star (MTS). There an `api` module was properly extracted. IMHO the batch dependency stuff is still open. We should file an issue for this in MTS and close this one instead. WDYT?

**Comment by hohwille** [comment]
See also https://github.com/oasp/my-thai-star/pull/69

**Comment by hohwille** [comment]
Can we consider this as done?
* an `api` module had been extracted from archetype and a `batch` module was added: https://github.com/oasp/oasp4j/tree/develop-2.x/templates/server/src/main/resources/archetype-resources
* dependencies like tomcat in `core` have been moved to profile: https://github.com/oasp/oasp4j/blob/develop-2.x/templates/server/src/main/resources/archetype-resources/core/pom.xml#L240
* Same applies also for MTSJ: https://github.com/oasp/my-thai-star/tree/develop/java/mtsj
* The old restaurant app is going to be deleted anyhow so no need to worry.

Therefore IMHO everything is done here. I will close this issue. In case I am missing anything please comment, point out and re-open this issue.
