### ISSUE TITLE
Issues with Application Template

### ISSUE THREAD

**Issue by MarcoRose** [oasp/oasp4j#392]
Project feedback on oasp4j maven archetype (application template)  (feedback was given by Jan Peter Richter if you need to ask questions):

Please correct/improve application template 
-      The generated class de.tollcollect.me.ABC.general.common.api.UserProfile contains  in the comment a {@link } to a class de.tollcollect.me.ABC.staffmanagement.dataaccess.api.StaffMemberEntity and a TODO
  - Is this comment still correct? Can I ever use the UserProfile (is it Best Practice or dead Restaurant-Code)?
-      In the child POMs the group-IDs are again in it (Eclipse complains, that they are duplication of the parent POMs)
  Simple throw out? (in the child POMs)
-      25 warnings because of unclean JavaDocs – you can of course simply enter something here; I would be happy if the generated code would be immediately correct documented.
-      3 Imports, 1 fields,  1 variables are never used – are they actually superfluous, or must something be programmed (and if so what)?
- BeansJpaConfiguration receives an EntityManagerFactory injected, but seems not to use it.
- The ApplicationObjectMapperFactory has an attribute subtypes –This is probably only needed if there are such attributes. But can I delete it, or is it accessed per reflection on it? (In that case this schould be in a comment)
-     In the module ABC-core I can find under: 
  - src/main/resources/db/migration/h2 the configuration of the Restaurant-database. I would prefer an empty configuration here. 
  - src/main/resources/config/app/batch I can find two configrations, that are probably Restaurant-Batches (billexport and produktimport) 
  - src/main/resources/config/app I can find in application.properties the server.context-path=/oasp4j-sample-server. I would have liked to have here <name> 
  - the index.html contains <a href="services/rest/tablemanagement/v1/table/101">1. Table</a>
  - src/main/resources/application.properties contains spring.application.name=restaurant

**Comment by SimonHuber** [comment]
Comment:

> The generated class de.tollcollect.me.ABC.general.common.api.UserProfile contains in the comment a {@link } to a class de.tollcollect.me.ABC.staffmanagement.dataaccess.api.StaffMemberEntity and a TODO
Is this comment still correct? Can I ever use the UserProfile (is it Best Practice or dead Restaurant-Code)?

_The oasp4j restaurant sample does not contain the class de.tollcollect.me.ABC.general.common.api.UserProfile. Could you please clarify how this class is related to the project._



> In the child POMs the group-IDs are again in it (Eclipse complains, that they are duplication of the parent POMs) Simple throw out? (in the child POMs)

_Child POMs either don't have their own group-ID ([modules/pom.xml] (../blob/develop/modules/pom.xml)) or the group-ID ([samples/batch/pom.xml] (../blob/develop/samples/batch/pom.xml#L10)) is different to that from the parent POM ([pom.xml] (../blob/develop/pom.xml#L5))._







>  25 warnings because of unclean JavaDocs – you can of course simply enter something here; I would be happy if the generated code would be immediately correct documented.

_Warnings concerning missing comments are still present.  A lot of warnings come from the builders package whose files are automatically generated. So how should this issue be treated?_



>  3 Imports, 1 fields, 1 variables are never used – are they actually superfluous, or must something be programmed (and if so what)?

_Unused imports are automatically removed. Unsused variables do not appear and unused fields are removed in PR #480._

> BeansJpaConfiguration receives an EntityManagerFactory injected, but seems not to use it.

_Removed in PR #480._

> In the module ABC-core I can find under:
 - src/main/resources/db/migration/h2 the configuration of the Restaurant-database. I would prefer an empty configuration here.

_[V0001__R001_Create_schema.sql](../blob/develop/samples/core/src/main/resources/db/migration/h2/V0001__R001_Create_schema.sql) creates an empty schema without datasets. Is this what you intended?_


 >  - src/main/resources/config/app/batch I can find two configrations, that are probably Restaurant-Batches (billexport and produktimport)

_The files [beans-billexport.xml] (../blob/develop/samples/core/src/main/resources/config/app/batch/beans-billexport.xml) and [beans-productimport.xml](../blob/develop/samples/core/src/main/resources/config/app/batch/beans-productimport.xml) are the bean configuration files of [BillExportJobTest.java](../blob/develop/samples/core/src/test/java/io/oasp/gastronomy/restaurant/salesmanagement/batch/impl/billexport/BillExportJobTest.java) and [ProductImportJobTest.java](../blob/develop/samples/core/src/test/java/io/oasp/gastronomy/restaurant/offermanagement/batch/impl/productimport/ProductImportJobTest.java) which are necessary for running these two tests._

 

> - src/main/resources/config/app/batch I can find two configrations, that are probably Restaurant-Batches (billexport and produktimport)
the index.html contains 1. Table


_Could you please clarify what is meant._

> - src/main/resources/application.properties contains spring.application.name=restaurant

_Could you please clarify what is meant._

**Comment by sroeger** [comment]
With PR #485 and #480 these are the remaining tasks:

- In the module ABC-core I can find under:

 - src/main/resources/db/migration/h2 the configuration of the Restaurant-database. I would prefer an empty configuration here.
 - src/main/resources/config/app/batch I can find two configurations, that are probably Restaurant-Batches (billexport and productimport)
 - src/main/resources/config/app I can find in application.properties the server.context-path=/oasp4j-sample-server. I would have liked to have here
 - the index.html contains 1. Table
 - src/main/resources/application.properties contains spring.application.name=restaurant

We should clarify what kind of default configuration for the database/application.properties we could use for the template. And how the index.html could look like for a "fresh" project.

**Comment by hohwille** [comment]
Indeed very messy (see #629). Thanks for the feedback... I am about to resolve all the issues noted here...

**Comment by hohwille** [comment]
#629 has been merged. IMHO all aspects of this issue have been resolved.
