### ISSUE TITLE
Unified deploy for client and server on tomcat is not working with oasp2.0.0

### ISSUE THREAD

**Issue by ssarmokadam** [oasp/oasp4j#399]
I have created src/main/client directory in project oasp4j-sample-server and copied oasp4js client in it. After I build oasp4j-sample-server with maven jsclient profile, client is built successfully and copied to static folder. But if I will deploy oasp4j-sample-server war on tomcat and try to access url http://localhost:8081/oasp4j-sample-server/jsclient/ it is showing requested resource not available.

**Comment by hohwille** [comment]
Please give more details:
* are you talking about a new (empty) project?
* did you create that with maven archetype (oasp4j-template-server)?
* did you look into the WAR if the client is actually present in there and in what place?
* is any static content (index.html) served?

**Comment by jhcore** [comment]
You need to do some changes if you want to deploy the client and server together. I created this page in the wiki where you can do the changes https://github.com/oasp/oasp4js/wiki/tutorial-jspacking-angular-client

**Comment by amarinso** [comment]
This should have been closed when answered. Doing it now
