### ISSUE TITLE
The how-to documentation on JSON Custom Mappings is out-dated

### ISSUE THREAD

**Issue by Jan-PeterRichterCG** [oasp/oasp4j#400]
The how-to on JSON Custom Mappings in http://oasp.github.io/oasp4j/2.0.0/OASP4J.pdf appears a bit out-dated. The example tells me to create a RestaurantObjectMapperFactory extends ObjectMapperFactory but apparently there may be only one ObjectMapperFactory which is the ApplicationObjectMapperFactory. That class has been already created either by the Maven Template for OASP eclipse projects or the CobiGen for REST services. The code to register the custom serializer / deserializer from the documented how-to apparently works fine in the ApplicationObjectMapperFactory.

**Comment by hohwille** [comment]
https://github.com/oasp-forge/oasp4j-wiki/wiki/guide-json#json-and-inheritance

**Comment by hohwille** [comment]
Thanks for the feedback. The docu has been updated.
