### ISSUE TITLE
The documentation of OASP4J 2.0.0 referns to a sample logback.xml through a dead link

### ISSUE THREAD

**Issue by Jan-PeterRichterCG** [oasp/oasp4j#402]
The documentation http://oasp.github.io/oasp4j/2.0.0/OASP4J.pdf says  "OASP4J provides a production ready configuration here." where "here" links to https://github.com/oasp/oasp4j/blob/develop/oasp4j-samples/oasp4j-sample-server/src/main/resources/logback.xml which is a dead link.
The Wiki https://github.com/oasp/oasp4j/wiki/guide-logging links to https://raw.githubusercontent.com/oasp/oasp4j/develop/samples/server/src/main/resources/logback.xml which does.
Apparently, In order to fix this, a new version of the OASP4J 2.0.0 Documentation must be generated.

**Comment by hohwille** [comment]
Thanks for the feedback. We should not modify a release after it has been published.
Instead we should get the next release out that already fixes the problem.
