### ISSUE TITLE
packaging war includes libraries twice

### ISSUE THREAD

**Issue by MarcoRose** [oasp/oasp4j#405]
In the current version of the OASP all libraries seem to be included twice ( core + server ) in the resulting War archive, when the application is build on the console with Maven. This results in a file size of approximately 100 MB.

As a solution we have chosen the following solution in the Toll Collect project:

The Scope of Dependencies in the Core project was changed to "provided", so that the dependencies from the core project are not tightened again in the server project.

**Comment by hohwille** [comment]
I missed this one and just created a duplicate with #407.

**Comment by hohwille** [comment]
What needs to be done is remove this `<plugin>` section from POM:
https://github.com/oasp/oasp4j/blob/develop/samples/core/pom.xml#L252

Then we need to revisit if this would have negative impact on `batch` that also needs some fix (I guess no):
https://github.com/oasp/oasp4j/blob/develop/samples/batch/pom.xml

**Comment by hohwille** [comment]
Done. AFAIK no impact on batch. All tests running, artifact size reduced massively.
