### ISSUE TITLE
OASP IDE Setup Settings/Scripts missing

### ISSUE THREAD

**Issue by tonqa** [oasp/oasp4j#408]
In the OASP IDE Setup Guide there is a link to the IDE distribution.
https://github.com/oasp/oasp4j/wiki/oasp-ide-setup 

However, since the distribution is provided via the Capgemini internal Teamforge page there is no download link to Zip-Files "scripts" and "settings" any more. This is crucial, because these Zip-files are needed for Setup of the IDE and there is no way to install OASP/Devon any more. Or did I miss something?

Also, I am currently installing an older version of OASP4j 1.x and I would enjoy it if it would be easier to find all distribution packages. Couldn't we provide a version matrix to find the matching versions of OASP4j, OASP4js, IDE, IDE-scripts, IDE-configs?

**Comment by hohwille** [comment]
In the docs you liked I can see:

> If you are not member of Capgemini: We cannot distribute the package. Please consult oasp4j-ide to setup and configure the IDE manually.

If I follow the link to oasp4j-ide I find the links to the scripts and settings files there:
https://github.com/oasp/oasp4j-ide/wiki/guide-script-package
https://github.com/oasp/oasp4j-ide/wiki/guide-settings

Both contain a direct link to m2 repo where you can download them.

> Also, I am currently installing an older version of OASP4j 1.x and I would enjoy it if it would be easier to find all distribution packages.

If you want to file a feature request for oasp4j-ide please go here:
https://github.com/oasp/oasp4j/issues

> Couldn't we provide a version matrix to find the matching versions of OASP4j, OASP4js, IDE, IDE-scripts, IDE-configs?

We are using git sub modules. If you are cloning oasp4j recursive then it will come with its corresponding settings and oasp4js version. Also the build is integrated if you just use `mvn clean install -P jsclient`.
So again I assume that this is more or less a matter of understanding the things properly.
BTW: We are totally aware of these problems and we are working on a version of `oasp4j-ide` based on OOMPH that will download and install you the IDE you need with everything set up properly completely automated. So far you have to go all the long way to read tightly through the docs.
