### ISSUE TITLE
QueryException on transient search criterion foreign id

### ISSUE THREAD

**Issue by mtransier** [oasp/oasp4j#409]
The following has been observed in the restaurant example application of OASP-2.0.
When you try to search for entities using a foreign id as a criterion (e.g., search for offers referencing a certain drink), the call fails bringing up the following exception:

`org.springframework.dao.InvalidDataAccessApiUsageException: org.hibernate.QueryException: could not resolve property: drinkId of: io.oasp.gastronomy.restaurant.offermanagement.dataaccess.api.OfferEntity [select count(offerEntity)
from io.oasp.gastronomy.restaurant.offermanagement.dataaccess.api.OfferEntity offerEntity
where offerEntity.drinkId = ?1];`

`drinkId` in this case is a transient property of `OfferEntity`which is calculated based on a `DrinkEntity`.

This can easily be reproduced by sending a POST to `http://localhost:8081/oasp4j-sample-server/services/rest/offermanagement/v1/offer/search` containing the following payload:
`{"drinkId":"1","pagination":{"page":1,"total":true}}`

**Comment by hohwille** [comment]
JPQL is simply wrong.
has to be `where offerEntity.drink.id = ?1` instead.
Does that come from a named query (I did not look in the code yet)?

**Comment by mtransier** [comment]
IIRC this query is created using Alias.$() (within some generated code).

**Comment by hohwille** [comment]
Sure. I will file an issue in the right place and close this one here then.

**Comment by hohwille** [comment]
Done. Should be fixed easily and quickly with the info provided here.
Thanks for your feedback.

**Comment by hohwille** [comment]
Seems I was too quick.
Not only the template is buggy. Also our sample:
https://github.com/oasp/oasp4j/blob/develop/samples/core/src/main/java/io/oasp/gastronomy/restaurant/offermanagement/dataaccess/impl/dao/OfferDaoImpl.java#L157

**Comment by kiran-vadla** [comment]
Hi Jörg

Your comment says that fix has to be done in template as well apart from the fix at https://github.com/oasp/oasp4j/blob/develop/samples/core/src/main/java/io/oasp/gastronomy/restaurant/offermanagement/dataaccess/impl/dao/OfferDaoImpl.java#L157. Can you please elaborate on the template fixing part ?

Thanks,
Kiran.

**Comment by ivanderk** [comment]
If you look at the issue Jörg referenced, you can see that it refers to the cobigen templates. Please refer to Sneha for further info and otherwise Ruben in Valencia (through Pablo).

**Comment by kiran-vadla** [comment]
@maybeec 

Will you please look into the PR made by Ruben for Cobigen templates fix ? 

Thanks,
Kiran.

**Comment by kiran-vadla** [comment]
@maybeec

To Add to my previous communication , as part of the fix for this issue (this was not oasp4j issue in fact) , Cobigen templates were fixed by Ruben and a PR was raised and assigned to you . Kindly look into it once you get a minute. 

Thanks,
Kiran.

**Comment by jomora** [comment]
@kiran-vadla, could you please provide references to issues or pull requests when you mention them?
You can provide them using the hash sign (#) and the according number.
For example, if you would like to reference this issue in another issue or PR use #409 (which does not work here since we're already looking at the issue)

**Comment by kiran-vadla** [comment]
@jomora , I don't have information on PR . Malte Brunnlieb has the information with respect to the pull request .

**Comment by kiran-vadla** [comment]
Cobigen templates fix by Ruben [PR- https://github.com/devonfw/tools-cobigen/issues/204 ]  was reviewed and approved by Malte Brunnlieb (@maybeec) .

**Comment by maybeec** [comment]
PR fixed.
