### ISSUE TITLE
AccessControlGroups in HashSet and changing hashCode

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j#418]
In #241 we discussed that custom implementations of `hashCode` cause trouble if you change the object after it has been added to a `Set` or `Map` as the `hashCode` changes what results in a situation where the object can neither be found in nor removed from the `Set` or `Map`.

In PR #410 this was discovered to be a problem in `AbstractAccessControlProvider`.
This issue should fix the problem (maybe by removing `hashCode` and `equals` implementations from `AccessControl` and its sub-classes.

**Comment by kiran-vadla** [comment]
Closing this as the same is addressed in PR #466
