### ISSUE TITLE
How to remove WSDL4J from OASP dependencies?

### ISSUE THREAD

**Issue by jomora** [oasp/oasp4j#419]
When excluding the dependency 
```xml
<dependency>
    <groupId>wsdl4j</groupId>
    <artifactId>wsdl4j</artifactId>
    <version>1.6.3</version>
</dependency> 
```
from OASP the following error occurs at runtime:
`lang.NoClassDefFoundError: javax/wsdl/WSDLException`

I pinned down the location of the problem to method `private T loadDefaultURIs(final String uri)` of class `org.apache.cxf.transport.TransportFinder<T>`, but due to a lack of understanding of the CXF framework I couldn't manage to dig deeper. 
The call stack looks as follows:
```
TransportFinder$3.loadBean(String, Class<? extends T>) line: 200	
ExtensionManagerImpl.loadBeansOfType(Class<T>, BeanLoaderListener<T>) line: 366	
SpringBeanLocator.loadBeansOfType(Class<T>, BeanLoaderListener<T>) line: 225	
TransportFinder<T>.loadDefaultURIs(String) line: 212	
TransportFinder<T>.findTransportForURI(String) line: 81	
DestinationFactoryManagerImpl.getDestinationFactoryForUri(String) line: 128	
JAXRSServerFactoryBean(AbstractJAXRSFactoryBean).createEndpointInfo(Service) line: 131	
JAXRSServerFactoryBean(AbstractJAXRSFactoryBean).createEndpoint() line: 219	
JAXRSServerFactoryBean.create() line: 165	
```
The method `JAXRSServerFactoryBean.create()` is called in method `public Server jaxRsServer()` of class  `io.oasp.gastronomy.restaurant.general.configuration.ServiceConfiguration`.

The goal is to completely exclude WSDL4J. (It might be replaced by a custom implementation, but this is to be decided later)

Does anyone have an idea or hint on this issue?
Thanks in advance!

PS: please also have a look at the following conversation:
https://www.yammer.com/capgemini.com/#/Threads/show?threadId=689687591

**Comment by hohwille** [comment]
Can we close this as invalid (or wontfix)?
This is a required dependency for CXF.

**Comment by sobkowiak** [comment]
for me :+1:
