### ISSUE TITLE
Missing AUTO_INCREMENT in Column "id" of RESTAURANTTABLE in Sample Application

### ISSUE THREAD

**Issue by jomora** [oasp/oasp4j#423]
In line 65 of [V0001__R001_Create_schema.sql](https://github.com/oasp/oasp4j/blob/develop/samples/core/src/main/resources/db/migration/h2/V0001__R001_Create_schema.sql#L65) there is no `AUTO_INCREMENT` specified for column `id`. This causes any save operation on a new `TableEntity` (where `id = null`) to fail with the following exception:
`org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement`

I was not able to find any documentation on whether this behaviour is intended or not.
Due to the fact that `TablemanagementImpl#saveTable` is present and properly implemented this behaviour occurs to me as a bug.

Do you agree or did I miss something?

**Comment by hohwille** [comment]
Thanks for the feedback. You found a bug introduced by #317 (and PR #396).
It would be awesome if you could go through the SQL, fix it (add *all* missing `AUTO_INCREMENT`) and provide a pull-request for this.

**Comment by sroeger** [comment]
This issue is solved by PR #429 and #432.
