### ISSUE TITLE
oasp4j-example-application: can not build because pom referencing not existing parent pom

### ISSUE THREAD

**Issue by joedoehh** [oasp/oasp4j#43]
issue:
unable to build example application using both maven from command line ("maven clean install") or in eclipse with m2e plugin

root cause:
1: oasp4j-example-application/pom.xml is referencing non-resolvable parent pom

  <parent>
    <groupId>org.oasp.java</groupId>
    <artifactId>oasp4j-example</artifactId>
    <version>1.0.0-SNAPSHOT</version>
  </parent>

2: oasp4j-sample/pom.xml is referencing non-resolvable parent pom
  <parent>
    <groupId>org.oasp.java</groupId>
    <artifactId>oasp4j</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <relativePath>../oasp4j/pom.xml</relativePath>
  </parent>

expected fix:
from my understanding
1: oasp4j-example-application/pom.xml can not reference oasp4j-sample/pom.xml, the latter is nox existing as it can not be build because of error 2 -> solving the issue stopping oasp4j-sample/pom.xml from being build should also fix this problem

2: oasp4j-sample/pom.xml can not reference oasp4j/pom.xml as oasp4j/pom.xml is defined to be adressable with the following maven coordinates:

  <groupId>org.oasp.java</groupId>
  <artifactId>oasp4j-dependencies</artifactId>
  <version>1.0.0-SNAPSHOT</version>

so referencing this pom using coordinates

```
<groupId>org.oasp.java</groupId>
<artifactId>oasp4j</artifactId>
<version>1.0.0-SNAPSHOT</version>
<relativePath>../oasp4j/pom.xml</relativePath>
```

can not work because of wrong artifactId. it should be using, <artifactId>oasp4j-dependencies</artifactId> right?!?!

as this is a fundamental change in the build setup i am reluctant from simply fixing and checking in my suggested fix and ask for some educated advice - is my assumption wrong or do i follow the wrong steps in building the application? from the given state checked in ci and all other users seem to be able to build the application, but i simply dont get it where i am wrong and dont want to break the running build. or maybe there is something in the maven pom tree submodules hirarchies that i am not able to see or understand how it works

**Comment by oelsabba** [comment]
@joedoehh  Thanks for filing this issue. Do still have the same problem? 
I am currently facing the same problem "Project build error: Non-resolvable parent POM". This happens in Projects: oasp4j-example-application and oasp4j-example-application-integration. Would appreciate if you share your solution for the problem.

**Comment by joedoehh** [comment]
@oelsabba after i moved to a new computer and because of some restructerings i just freshly successfully set up oaspj following the installation guide on https://github.com/oasp/oasp4j/wiki/oasp-ide-setup. i have not experienced the issues discussed here so i would consider it to be solved. 

Since i dont recall how i fixed the problem back then in september 2014 i would suggest to initially setup it again in your environment. Today i was using the oasp4j-xxx archives in version 1.3.0 and 1.3.1 and it worked out fine with no errors.
