### ISSUE TITLE
Bug in concept of flyway script src deployment

### ISSUE THREAD

**Issue by maybeec** [oasp/oasp4j#452]
In a training session, @narasam observed that we actually have an issue with our guideline for flyway to [update-database-script-files](https://github.com/devonfw/devon-guide/wiki/getting-started-set-up-and-maintain-database-schemas-with-flyway#update-database-script-files).

Especially, this issue is related to how we store the sql script. As we store commonly usable scripts in the root folder "migration" and just add db specific scripts to a subfolder, we will import all db specific scripts for any profile whenever running flyway. This is caused by the fact, that `flyway.locations` are scanning recursively for sql scripts.

So we have to change our file structure to move the commonly usable scripts in an additional subfolder like "migration/common" to prevent recurisvely scanning all folders by stating `flyway.locations=classpath:db/migration`

**Comment by hohwille** [comment]
The concept of OASP is different:
https://github.com/oasp-forge/oasp4j-wiki/wiki/guide-database-migration

The bug is "only" in the sample application.

See also https://github.com/flyway/flyway/issues/1192 and consider voting for it

**Comment by hohwille** [comment]
In order to cleanup our issues I am closing this one. According to the title description this issue is invalid. Feel free to open a new issue in MTS if something is invalid there.
