### ISSUE TITLE
Rework build script in server-template

### ISSUE THREAD

**Issue by sroeger** [oasp/oasp4j#453]
When adding custom packages to the restaurant sample those will be used in the template archetype. As in #449 one needs to manually exclude this folder in [build.xml](https://github.com/oasp/oasp4j/blob/develop/templates/server/build.xml) to get it build properly. 
We should rework the oasp4j-server-template build to make it work the other way around so it does only use explicitly _included_ packages.

**Comment by jomora** [comment]
@maybeec  could you please close this issue as #449 has been merged? Thanks :)

**Comment by hohwille** [comment]
PR was merged, hence closing.
