### ISSUE TITLE
Check oasp4j code formatting

### ISSUE THREAD

**Issue by maybeec** [oasp/oasp4j#454]
We observed some code formatting issues in #434 and #435.
- [ ] We should check, whether eclipse cleanup/formatter/save action is aligned to use the formatter configuration. 
- [ ] We should as well check if all code (including test code) is formatted according to the latest configuration. Please assure to use the eclipse release for that.

**Comment by jomora** [comment]
The latest OASP IDE release (2.1.x) is not yet available for download (although it should be AFAIK). Currently, the most actual version available is 2.0.0. This issue should be investigated when version 2.1.x of the IDE is available.

**Comment by hohwille** [comment]
If there is anything left that is wrong please file a concrete issue in oasp4j-ide (devon-ide). Thanks.
