### ISSUE TITLE
Release 2.1.1 Spring Boot build fails starting ...

### ISSUE THREAD

**Issue by maybeec** [oasp/oasp4j#477]
... with the following error message

```
no main manifest attribute, in oasp4j-sample-core-dev-SNAPSHOT.jar
```

**Comment by jomora** [comment]
After discussion in #478 this issue has become _invalid_. 
The behvaiour is actually desired.
It should _not_ be possible to start the core JAR in a standalone manner. Only the server should be used for running the sample application.
Therefore, I close the issue and add the tag __invalid__.

**Comment by maybeec** [comment]
open as not yet working since #491 has been merged

**Comment by maybeec** [comment]
I had the wrong assumption, that the core jar is already bootified. However, for those, that follow, there is a bootified war file in the samples/server build.
