### ISSUE TITLE
Browsing the rest wadl is broken

### ISSUE THREAD

**Issue by maybeec** [oasp/oasp4j#479]
Browsing the REST wadl of our deployed sample application is broken.
http://oasp-ci.cloudapp.net/oasp4j-sample/services?wadl

It refers to localhost as an endpoint address, which makes it impossible navigate.
Even more it just lists the service of the tablemanagement component.

**Comment by hohwille** [comment]
IMHO has been fixed long time ago. Anyhow the old restaurant has already been deleted.
