### ISSUE TITLE
spring-boot-maven-plugin mainClass issue

### ISSUE THREAD

**Issue by pablo-parra** [oasp/oasp4j#503]
Hi all,

I found a problem with the mainClass attribute  of the spring-boot-maven-plugin when creating new oasp4j apps using the oasp4j template (oasp4j archetype 2.1.0). 

After creating a new app with package _io.oasp.application.sampleapp_  I tried to launch it with `mvn spring-boot:run` command and I got the error

`Could not find or load main class io.oasp.gastronomy.sampleapp.SpringBootApp`

So the name of the main class of the new app doesn't match the name provided by the template in the `mainClass` attribute.

Changing that _mainClass_ to `io.oasp.application.sampleapp.SpringBootApp` the command `mvn spring-boot:run` works fine.

Regards
Pablo

**Comment by hohwille** [comment]
PR was merged. Issue therefore fixed. 
@pablo-parra thanks for the feedback/issue
@GawandeKunal Thanks for the great PR/fix 👍
