### ISSUE TITLE
log4j-over-slf4j.jar and slf4j-log4j12.jar conflitct

### ISSUE THREAD

**Issue by Siroque** [oasp/oasp4j#513]
In our environment we faced an issue:
java.lang.IllegalStateException: Detected both log4j-over-slf4j.jar AND bound slf4j-log4j12.jar on the class path
Which was caused by the dependency within core/pom.xml:
```
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-log4j12</artifactId>
      <version>1.6.1</version>
        <exclusions>
            <exclusion>
                <groupId>log4j</groupId>
                <artifactId>log4j</artifactId>
            </exclusion>
        </exclusions>
    </dependency>
```

Removing this dependency did the trick.

**Comment by hohwille** [comment]
No such dependency present (anymore):
https://github.com/oasp/oasp4j/blob/develop/samples/core/pom.xml

Was that meanwhile solved without updating this issue.
If there is no further feedback, we will close this issue in a while...

**Comment by hohwille** [comment]
Closing due to no further feedback. IMHO not an issue of OASP (anymore). Otherwise provide details and reopen.
