### ISSUE TITLE
JavaDoc JDK 8: class file for javax.interceptor.InterceptorBinding not found

### ISSUE THREAD

**Issue by jomora** [oasp/oasp4j#515]
In #499 a problem has been discovered. 

The `mvn site` command fails due to 
```txt
[ERROR] javadoc: error - com.sun.tools.doclets.internal.toolkit.util.DocletAbortException: com.sun.tools.javac.code.Symbol$CompletionFailure: class file for javax.interceptor.InterceptorBinding not found
```

By adding 
``` xml
<profiles>
  <profile>
    <id>doclint-disabled</id>
    <activation>
      <jdk>[1.8,)</jdk>
    </activation>
    <properties>
      <javadoc.params>-Xdoclint:none</javadoc.params>
    </properties>
  </profile>
</profiles>
```
to the top-level `pom` the problem vanishes. Unfortunately, this is not a proper solution since adding a dependency to the top-level `pom` inherits such a dependency to all sub-modules.
Please refere to #499 for more information.

Since we currently build the OASP4J on JDK 7 no problem arises w.r.t. to the interceptor binding. However, in the near futuer OASP4J will be built on JDK 8 and so this problem will come up sooner or later.

**Comment by hohwille** [comment]
I build the entire site with JDK8 and got no issues. Any further insights? Otherwise I will close this issue...
