### ISSUE TITLE
Reserved word problem with envers (AdvancedRevisionEntity)

### ISSUE THREAD

**Issue by guic** [oasp/oasp4j#535]
We are using oasp4j with a postgreSQL database and we have a problem with envers' auditing.
The insertions in RevInfo fail because "user" is a reserved word in PostgreSQL.

The problem comes from the AdvancedRevisionEntity class. 
Specifically the line "@Column(name = "\"user\"")" that has been commented out.
A note in the code tells us to uncomment it in case of an Oracle 11g database but it's really unpractical to have to make a fork just to change this. 
The annotation is effective with postgreSQL and should be we other databases. 

@geoffroya

**Comment by hohwille** [comment]
@guic Thanks for your feedback.
That problem has already been solved quite some time ago but nobody seemed to care about this ticket so far. Sorry for that.
Here you can see the fixed code:
https://github.com/oasp/oasp4j/blob/develop/modules/jpa-envers/src/main/java/io/oasp/module/jpa/dataaccess/api/AdvancedRevisionEntity.java#L49
