### ISSUE TITLE
Provide solution for missing parameter MaxPermSize in Java 8

### ISSUE THREAD

**Issue by jomora** [oasp/oasp4j#537]
#536 introduces line 
```xml 
<argLine>-Xmx1024m -XX:MaxPermSize=256m</argLine>
```

Since `MaxPermSize` is not available in Java 8 ([check this out](http://docs.oracle.com/javase/8/docs/technotes/tools/windows/java.html)), we have to find a proper solution and remove this workaround.

**Comment by maybeec** [comment]
you can simply remove it for java8

**Comment by hohwille** [comment]
Yep, with J8 there is no perm space and hence this config can be dropped.
We could retry without the option with recent J7 and see if that also works. If so we can generally drop it. Otherwise add a comment for J8 telling to remove it on error. You might also want to build jdk driven profiles.

**Comment by hohwille** [comment]
Indeed does not work on J7 without the option.
MTSJ is not affected at all:
https://github.com/oasp/my-thai-star/blob/develop/java/mtsj/pom.xml#L143

So as the entire restaurant sample will be deleted very soon and is already replaced with MTS I will simply close this issue as wontfix.
