### ISSUE TITLE
Creating 2 module with Spring Boot Main class

### ISSUE THREAD

**Issue by darkmanAmazigh** [oasp/oasp4j#538]
Hi,
We can create 2 module with Spring Boot Main class using OASP ?
Actually i can't create theme.
i mean :
ParentProject
                      - core
                      - batch
                      - server

Thank you

**Comment by jomora** [comment]
Hey, your request is quite vague not understandable without a more detailed description. Please, provide such a description such that we can discuss your request.

**Comment by hohwille** [comment]
As we did not receive any feedback for almost a year, I am closing once more. If you want to reopen, ensure to give exact details how to reproduce with the latest release. From my tests it is working properly...
