### ISSUE TITLE
Introduction of new version of hibernate envers jar in oasp4j-jpa-envers module.

### ISSUE THREAD

**Issue by PriyankaBelorkar** [oasp/oasp4j#540]
we use Envers in OASP4J to do auditing of the database as described in the Devonfw Guide paragraph 3.12.2 “Auditing with Hibernate Envers”., the issue relates to some instances that the database is at application startup in read-only mode or the REVINFO (which Envers uses) is not present. This leads to an application crash.
So, for this problem , we need to have a property in applications.properties which allows us to disable the envers mechanism so that the application will not crash. 

The property which is used to enable/disable envers is available in hibernate-envers-5.0.1-Final.jar but not in the existing one being used.
So , introduction of newer version should be done.

**Comment by hohwille** [comment]
@PriyankaBelorkar thanks for your feedback and sorry for the extra ordinary late response.
We will surely update envers dependency to an even more recent version than you proposed. I hope and plan to have that in `3.0.0` where we also do major updates to spring and spring-boot anyways.
Link to the place:
https://github.com/oasp/oasp4j/blob/develop/bom/pom.xml#L119

**Comment by hohwille** [comment]
BTW: I am quite sure you managed to find a way to override and upgrade yourself in your project POM anyways :)

**Comment by hohwille** [comment]
See PR #668 that solves this issue.

**Comment by hohwille** [comment]
PR #668 was merged, hence done.
