### ISSUE TITLE
Running bootified war *with* integrated client from command line does not work

### ISSUE THREAD

**Issue by ivanderk** [oasp/oasp4j#544]
When using a bootified war with integrated javascript client, while running it it from the command line, the bootified war does not properly publish the javascript client

Errors and details in attached PDF
[WAR deployment.pdf](https://github.com/oasp/oasp4j/files/774259/WAR.deployment.pdf)

**Comment by GawandeKunal** [comment]
Started looking into it.

**Comment by hohwille** [comment]
Can we close this as wontfix? IMHO the new MTS is the way to go and does not have such issues. Restaurant sample is dead and should be deleted in the future.
Do you agree and could close with label wontfix?
