### ISSUE TITLE
h2 scripts in oasp4j\samples\core\src\main\resources\db\migration\h2 are not getting copied to corresponding directory in templates project

### ISSUE THREAD

**Issue by kiran-vadla** [oasp/oasp4j#552]
h2 scripts in oasp4j\samples\core\src\main\resources\db\migration\h2 are not getting copied to the corresponding directory in templates module in oasp4j. 

When the sample application created from the oasp4j maven archtype is imported in Eclipse Neon and SpringBootApp is launched, we receive an error because of 'user' column in RevInfo table that is defined in DDL script oasp4j\samples\core\src\main\resources\db\migration\h2\V0001__R001_Create_schema.sql. This column is defined as userName in the same script in oasp4j\samples modules. 

Attached is the stack trace of the error that we receive when we launch SpringBootApp. 

Thanks,
Kiran. 
[error.txt](https://github.com/oasp/oasp4j/files/847098/error.txt)

**Comment by jomora** [comment]
Just merged #554. Therefore, I'll close this issue aswell.
