### ISSUE TITLE
create sample batch and batch documentation (guide) based on JSR352

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j#56]
For batches we want to suggest using JSR352 with spring-batch as implementation.
However there are a lot of additional best practices and we want to have a sample batch to show how to do it properly.
I already talked to Vishal who will take over this topic.
As scenario we picked a batch that will generate a report of all orders and order positions (potentially inc. bills) for the last X years or since X (X could be configurable as parameter when the batch is invoked).
According to KISS we will put this directly in the sample application. For a real deployment a separate maven project could use dependency plugin extract the war and bundle this in a deployment artifact together with a shell script to start the batch.
This will cause some batch dependencies being in the war that might not be needed on the server and also some war dependencies that will be in the batch deliverable that might not be needed.
Otherwise we would have to modularize the sample into 3 projects:
* core (jar)
* app (war depends on core)
* batch (jar depends on core)

As the extra dependencies do not really hurt we want to go for KISS. If there is a good argument why this is unacceptable, let us know.

**Comment by jczas** [comment]
This task has been started in branch feature/batch.
In first step we are going to implement some example jobs.

**Comment by hohwille** [comment]
@jczas great to hear that you are getting started.
Can you please use a fork and provide the result in the end as pull-request.
That would be the official workflow of OASP that we are now using...
Thanks!

**Comment by hohwille** [comment]
https://github.com/oasp/oasp4j/wiki/oasp-code#code-contribution

**Comment by MarcoRose** [comment]
First batch reference implementation released with oasp4j 1.5.0. Thank you!
