### ISSUE TITLE
Prefix All abstract classes with Abstract in the name

### ISSUE THREAD

**Issue by kiran-vadla** [oasp/oasp4j#561]
This PR will address the the task of Prefixing all abstract classes with Abstract in the name .

**Comment by jomora** [comment]
@kiran-vadla I'm not sure whether this is a reasonable task. For example, in #550 @hohwille states 

> However not every abstract class shall be named with an Abstract prefix. This is not done consistently by jdk, nor by spring, etc.

So, in general not every abstract class needs this prefix.
@hohwille gives an example for such classes: 

> We are already offering classes such as ModuleTest or ComponentTest that are also abstract but do not carry this prefix. So I do not see a problem here.

I think we should not take the discussion regarding #550 (also in Yammer) to change everything that is already in place.

**Comment by amarinso** [comment]
Why not? it is not done consistently in other projects... but we may prefer to be a bit more consistent here if we have the chance...

As I stated, I prefer to look for clases prefixed with Abstract when in the IDE, for example starting a new test I can `extend AbstractTest` (ctrl+space) to get help

![image](https://cloud.githubusercontent.com/assets/9352103/25225533/fc4dcb2e-25c1-11e7-97c3-6a4b7ea7118c.png)

(note here I've already renamed the classes to have the prefix and they are shown nicely together)

**Comment by jomora** [comment]
@amarinso I got it! :-) Thanks for the clarification!

@kiran-vadla Let's do this! :-)

**Comment by amarinso** [comment]
Close this as the PR was merged
