### ISSUE TITLE
List of dependencies that can be excluded from Spring Boot BOM that comes with OASP4J maven template

### ISSUE THREAD

**Issue by kiran-vadla** [oasp/oasp4j#567]
To come up with list of dependencies that can be excluded from Spring Boot BOM that comes with OASP4J maven template.

**Comment by kiran-vadla** [comment]
List of dependencies that can be excluded from Spring Boot/OASP4J  are as follows : 

asm-4.2.jar
bridge-method-annotation-1.13.jar
commons-codec-1.9.jar
commons-collections-3.2.2.jar
commons-compiler-2.7.8.jar
commons-lang3-3.2.1.jar
commons-logging-1.2.jar
httpcore-4.4.5.jar
janino-2.7.8.jar
jboss-logging-annotations-1.2.0.Beta1.jar
jboss-transaction-api_1.2_spec-1.0.0.Final.jar
jsr305-1.3.9.jar
jstl-1.2.jar
jul-to-slf4j-1.7.21.jar
log4j-over-slf4j-1.7.21.jar
scala-library-2.10.4.jar
snakeyaml-1.16.jar
woodstox-core-asl-4.4.1.jar
stax2-api-3.1.4.jar
tomcat-embed-core-8.0.37.jar
tomcat-embed-core-8.0.37.jar
tomcat-embed-el-8.0.37.jar
tomcat-embed-logging-juli-8.0.37.jar
tomcat-embed-websocket-8.0.37.jar
tomcat-jdbc-8.0.37.jar
tomcat-juli-8.0.37.jar
cxf-rt-bindings-xml-3.1.8.jar
cxf-rt-ws-addr-3.1.8.jar
cxf-rt-ws-policy-3.1.8.jar
spring-retry-1.1.3.RELEASE.jar
spring-oxm-4.2.8.RELEASE.jar
spring-jms-4.2.8.RELEASE.jar
spring-integration-core-4.2.9.RELEASE.jar
spring-boot-starter-web-1.3.8.RELEASE.jar
spring-boot-starter-validation-1.3.8.RELEASE.jar
spring-boot-starter-security-1.3.8.RELEASE.jar
spring-boot-starter-jdbc-1.3.8.RELEASE.jar

Thanks,
@kiran-vadla

**Comment by amarinso** [comment]
By maven template you mean the application archetype?

**Comment by kiran-vadla** [comment]
Correct @amarinso 

Thanks,
@kiran-vadla

**Comment by kiran-vadla** [comment]
Hi @amarinso, This applies to sample restaurant application as well . I have excluded these dependencies in server project using 'dependencyManagement' tag and using the scope 'provided' and tested the sample restaurant application with Angular and Sencha clients in tomcat .

Will be raising a PR for the same in short while.      

Thanks,
@kiran-vadla

**Comment by kiran-vadla** [comment]
closing this issue as PR #573 is reviewed and merged.
