### ISSUE TITLE
WebConfig.java has a dependency with catalina (tomcat) for SetCharacterEncodingFilter

### ISSUE THREAD

**Issue by amarinso** [oasp/oasp4j#577]
When trying to deploy without Tomcat dependencies this class refuses to compile and is because the direct dependency with `org.apache.catalina.filters.SetCharacterEncodingFilter` on tomcat-embed-core-xx.jar

**Comment by kiran-vadla** [comment]
Hi @amarinso , I will be addressing this issue as part of the PR #576 

Thanks,
@kiran-vadla

**Comment by kiran-vadla** [comment]
Hi @amarinso , I have submitted the fix as part of PR #576. Please check. 

Thanks, 
@kiran-vadla

**Comment by amarinso** [comment]
As commented there, it should be on their own PR because it does not make sense to add in an non-related PR

**Comment by kiran-vadla** [comment]
Hi @amarinso , I have addressed this issue in a separate PR #581 . Please review the same.

**Comment by amarinso** [comment]
Solved by Kiran for 2.4.0
