### ISSUE TITLE
OASP4j wiki doesn't appear updated for version 2.3.0

### ISSUE THREAD

**Issue by amarinso** [oasp/oasp4j#579]
When reviewing Issue #546 I notice that oasp4j wiki seems not to be updated

Page on the forge:
`https://github.com/oasp-forge/oasp4j-wiki/wiki/tutorial-newapp#from-command-line`

has referencences to the 2.3.0 release

but looking at:
`https://github.com/oasp/oasp4j/wiki/tutorial-newapp#from-command-line`

references to 2.2.0 which is not current

**Comment by kiran-vadla** [comment]
Hi @amarinso , fixed this . Please check https://github.com/oasp/oasp4j/wiki/tutorial-newapp#from-command-line now.

**Comment by amarinso** [comment]
Thanks Kiran, closing this
