### ISSUE TITLE
Document the usage of UserDetailsService of Spring Security

### ISSUE THREAD

**Issue by kiran-vadla** [oasp/oasp4j#584]
Document the usage of UserDetailsService of Spring Security in OASP4J wiki.

**Comment by AbhayChandel** [comment]
Hi @kiran-vadla, @amarinso, I have documented the usage of UserDetailsService in OASP4J at https://github.com/devonfw/devon-guide/wiki/cookbook-security-layer#spring-security-apis-and-their-usage-in-oasp4j. Review the same and let me know.

thanks
@AbhayChandel

**Comment by AbhayChandel** [comment]
Hi @amarinso, @kiran-vadla, I have documented the UserDetailsService and also updated the documentation on OASP4J security at https://github.com/devonfw/devon-guide/wiki/cookbook-security-layer. Please review the same as soon as possible and let me know.

thanks
@AbhayChandel

**Comment by kiran-vadla** [comment]
Hi @AbhayChandel , I have modified little , the section 'Authentication' for In-memory authentication and the section 'Spring Security APIs and their usage in OASP4j' for the Spring documentation of UserDetailsService. Otherwise , rest of the wiki looks good. 

Thanks,
@kiran-vadla

**Comment by kiran-vadla** [comment]
closing this issue as the wiki on OASP4J security at https://github.com/devonfw/devon-guide/wiki/cookbook-security-layer looks good. 

Thanks,
@kiran-vadla
