### ISSUE TITLE
OASP integrated Build with JavaScript Client

### ISSUE THREAD

**Issue by ivanderk** [oasp/oasp4j#586]
Based on a mail send by Jörg Hohwiller,

We should use frontend-maven-plugin to build the client integrated with the server. This should happen in the regular build of the SAMPLE application. The change should integrate the OASP4js client dist directly into the WAR file. There should also be a profile to integrate the sencha app. 

Profiles should be:

- jsclient                   - oasp4j + oasp4js
- senchaclient           - oasp4j + sencha client
- servicelayer            - oasp4j

while using jsclient by default (activeProfile)

https://github.com/oasp/oasp4j/blob/develop/samples/server/pom.xml#L30

To get started:
…
    
    <js.build.tool>npm</js.build.tool>
    <js.node.version>v5.12.0</js.node.version>
    <js.npm.version>3.5.2</js.npm.version>
    <js.yarn.version>v0.21.3</js.yarn.version>
  </properties>

…
      <build>
        <plugins>
          <plugin>
            <groupId>com.github.eirslett</groupId>
            <artifactId>frontend-maven-plugin</artifactId>
            <configuration>
              <workingDirectory>${js.client.dir}</workingDirectory>
            </configuration>
            <executions>
              <execution>
                <id>js-client-install-tools</id>
                <phase>generate-sources</phase>
                <goals>
                  <goal>install-node-and-${js.build.tool}</goal>
                </goals>
                <configuration>
                  
                  <nodeVersion>${js.node.version}</nodeVersion>
                  <npmVersion>${js.npm.version}</npmVersion>
                  <yarnVersion>${js.yarn.version}</yarnVersion>
                </configuration>
              </execution>
              <execution>
                <id>js-client-install-dependencies</id>
                <phase>generate-sources</phase>
                <goals>
                  <goal>${js.build.tool}</goal>
                </goals>
                <configuration>
                  <arguments>install</arguments>
                </configuration>
              </execution>
              <execution>
                <id>js-client-gulp-clean</id>
                <phase>generate-sources</phase>
                <goals>
                  <goal>gulp</goal>
                </goals>
                <configuration>
                  <arguments>clean</arguments>
                </configuration>
              </execution>
              <execution>
                <id>js-client-gulp-build</id>
                <phase>generate-sources</phase>
                <goals>
                  <goal>gulp</goal>
                </goals>
                <configuration>
                  <arguments>build:dist</arguments>
                </configuration>
              </execution>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>

**Comment by ivanderk** [comment]
See: https://github.com/oasp/oasp4j/issues/214

**Comment by ivanderk** [comment]
When closing, please close https://github.com/oasp/oasp4j/issues/214 as well

**Comment by kiran-vadla** [comment]
As discussed in the Architects meet today , because of the time constraints and complexity , this is being moved to oasp4j-3.0.0 release. 

Thanks,
@kiran-vadla

**Comment by hohwille** [comment]
IMHO for restaurant sample this makes no sense any more. For MTS this is more or less already in place.
The only thing left to go is IMHO to redesign the archetypes with this in mind so we could offer an archetype for full-stack development with oasp4js + oasp4j in combination.
IMHO we should clarify this, create a new story issue for that and close all this. 
WDYT?

**Comment by hohwille** [comment]
I have created #619 as a replacement and close this issue as duplicate.
