### ISSUE TITLE
Travis CI build fails with error: "JAVA_HOME should point to a JDK not a JRE"

### ISSUE THREAD

**Issue by preichel-cg** [oasp/oasp4j#602]
Hello, I stumbled over this while working on my PR #594 .
After discussion with Jörg I tried to fix the setup of the file`oasp4j/.travis.yml` .

Searching through GitHub there seem to be a few solutions:
(from: https://github.com/travis-ci/travis-ci/issues/7019#issuecomment-316769716 and https://github.com/travis-ci/travis-ci/issues/7884#issuecomment-308451879 )

1. switch from default `dist: trusty` to `dist: precise`
2. switch from `oraclejdk7` to `openjdk7`
3. switch to `oraclejdk8` with `sudo: required`

I already tried 1. - which seemed least invasive to me - and it worked, so I will provide a PR. (But feel free to fix it differently.)

Cheers, Patrick

**Comment by hohwille** [comment]
was already fixed and now works like a charm.
@preichel-cg thanks again for your help and fix 👍
