### ISSUE TITLE
Context Root of generated Project should be set to the Maven Application Name

### ISSUE THREAD

**Issue by cczaja** [oasp/oasp4j#604]
It is quite confusing having oasp4j-sample-server as default context root after generating new application. I would expect that it is set to the Maven application name.

**Comment by hohwille** [comment]
I raised the same question internally and fully agree with you.
However my-thai-star (MTS) is the new successor: 
https://github.com/oasp/my-thai-star
We appreciate any feedback on MTS in its own issue tracker, but we consider restaurant sample as a dead end and will delete it soon (H1 2018).
