### ISSUE TITLE
What is the reason for DatabaseMigrator and BeansJpaConfig

### ISSUE THREAD

**Issue by geoffroya** [oasp/oasp4j#605]
Hi all,

Can someone explain the rationale for having DatabaseMigrator and BeansJpaConfig, instead of just overriding FlywayMigrationStrategy?

Best regards

Geoff.

**Comment by hohwille** [comment]
Link:
https://github.com/oasp/oasp4j/blob/master/samples/core/src/test/java/io/oasp/gastronomy/restaurant/general/dataaccess/impl/config/BeansJpaConfig.java#L18

IMHO there is no good reason for this. However, restaurant sample is kind of a dead-end. We have my-thai-star (MTS) in place as a reasonable successor.
In 2018 we will delete the restaurant sample and entirely go for MTS as our new sample and reference.
Hence, I will close this as polishing a dead project is pointless.
Thanks for your feedback and I agree with you but better give feedback and enhancement suggestions about MTS instead:
https://github.com/oasp/my-thai-star

**Comment by geoffroya** [comment]
@hohwille => Actually they are part of the Archetype. I duplicate this to MTS as these classes still exist. IMHO FlywayMigrationStrategy is the good practice for Flyway, no?
