### ISSUE TITLE
Provide an use case for JMS usage in sample

### ISSUE THREAD

**Issue by sobkowiak** [oasp/oasp4j#63]
We need an use case to be implemented as a sample usage of sending/receiving jms messages.

**Comment by sobkowiak** [comment]
Any progress in this thema?

**Comment by sobkowiak** [comment]
@hohwille Do we have already an use case where we can use JMS? Perhaps we should start a new thread about this in our discussion forum?

**Comment by hohwille** [comment]
Like #64. Besides some nice wishes that "we should have something" unfortunately nothing happened. Every body is more than invited to bring his project experience into a reasonable business scenario in MTS as well as provide some module with glue code or helpers as needed into devon4f.
