### ISSUE TITLE
Decide for JMS broker

### ISSUE THREAD

**Issue by sobkowiak** [oasp/oasp4j#64]
If OASP4J based application will be deployed on an application server then the JMS implementation provided by the server should be used. In case the application will be deployed on web container should recommend a JMS broker which can be used for the application. We should also provide this broker in our sample application. 

This issue is to start a discussion about broker we should use.

**Comment by sobkowiak** [comment]
HornetQ has contributet the source code to Apache ActiveMQ project and both communities have been merged. HornetQ is now a subproject of ActiveMQ known as [ActiveMQ Artemis](http://activemq.apache.org/artemis/).  The further development of HornetQ in old community has been discontinued (only the last branches 2.3.x and 2.4.x are in maintenance mode)

**Comment by hohwille** [comment]
JMS is a sad topic of OASP. I did not have the background and time to work on support, guides and examples. However, no one else also came up with it. I will close this here. Feel free to contribute to devonfw (devon4j) that is the successor of oasp (oasp4j).
