### ISSUE TITLE
Upgrade to Flyway 4

### ISSUE THREAD

**Issue by AbhayChandel** [oasp/oasp4j#640]
OASP version `3.0.0` will come with flyway 5. Currently we still have flyway 3. There are issues upgrading from 3 to 5 so you first need an intermediate upgrade to flyway 4 first:
https://stackoverflow.com/questions/49945098/how-to-upgrade-from-flyway-3-directly-to-flyway-5

Of course any user can do an upgrade to flyway 4 on its own. But we should support our users so that the next release is shipped with flyway 4. When they upgrade to OASP version `2.6.0` and later to `3.0.0` and bring both states into production then everything should work smooth. This should be stated clearly in the release notes of both versions.

**Comment by hohwille** [comment]
See also https://github.com/oasp/my-thai-star/pull/108

**Comment by AbhayChandel** [comment]
Flyway upgraded to 4.2.0 for OASP4J and My Thai Star

**Comment by hohwille** [comment]
For the record:
* https://github.com/oasp/oasp4j/blob/develop-2.x/templates/server/src/main/resources/archetype-resources/pom.xml#L15
* https://github.com/oasp/oasp4j/commit/a3120aa1ea9e9afe879859a1f703088e07690e55
