### ISSUE TITLE
Column type Bytea error for PostgreSQL

### ISSUE THREAD

**Issue by AbhayChandel** [oasp/oasp4j#643]
When testing PR#629 with Postgresql version 9.6.9 & 10.4, error : found [bytea (Types#BINARY)], but expecting [oid (Types#BLOB)] encountered in column [content] in table [BinaryObject]
[bytea_postgresql_error.txt](https://github.com/oasp/oasp4j/files/2011552/bytea_postgresql_error.txt)

**Comment by vapadwal** [comment]
Closing this issue as the issue was because project was not created properly
