### ISSUE TITLE
Change groupId for devon4j-bom to com.devonfw.java.boms

### ISSUE THREAD

**Issue by AbhayChandel** [oasp/oasp4j#653]
Recently there has been change in BOMs' structure due to addition of new BOM(oasp4j-minimal-bom). To improve upon existing structure for oasp4j-boms module it is suggested that groupId "io.oasp.java" for "oasp4j-bom" be changed to "io.oasp.java.boms".

**Comment by hohwille** [comment]
Fine. Would you be able to provide a PR?

**Comment by hohwille** [comment]
According to #662 and the fact that OASP will be replaced by Devon this is IMHO not necessary for 3.0.0. We can also move this to the devon namespace refactoring. If none disagrees or brings valid arguments against it, I will move this to according milestone next week.

**Comment by AbhayChandel** [comment]
Agree I think we can wait another month to fix this once and for all.

**Comment by hohwille** [comment]
Done in devon4j.
