### ISSUE TITLE
Wrong OASP4J version in template/archetype

### ISSUE THREAD

**Issue by AbhayChandel** [oasp/oasp4j#654]
Currently OASP4J version in template/archetype-resources is 2.6.0 should be 2.6.1-SNAPSHOT.

**Comment by AbhayChandel** [comment]
@hohwille this project is not part of oasp4j inheritance tree hence cannot use the variables defined in oasp4j.  Values required have been set explicitly in this project.

**Comment by AbhayChandel** [comment]
fixed in #652.

**Comment by hohwille** [comment]
I will provide a PR that fix this issue in a way that we do not have to maintain the version redundantly anymore and will prevent further problems with this.

**Comment by hohwille** [comment]
Fixed with PR #656.
