### ISSUE TITLE
Remove manual upgrade to Flyway 4

### ISSUE THREAD

**Issue by AbhayChandel** [oasp/oasp4j#664]
For OASP4J release 2.6.0 we manually upgraded _Flyway_ to 4.2.0((#640 ) as _Spring boot_ 1.5.x did not support _Flyway_ higher than 3.x. We can now remove that change with  upgrade to Spring boot 2(#620 ) as it supports Flyway 5.x.

**Comment by hohwille** [comment]
Please keep in sync with #459. IMHO #664 or #459 should be closed as duplicate.

**Comment by hohwille** [comment]
Done.
