### ISSUE TITLE
Angular 6 template fails as it uses GET method of login

### ISSUE THREAD

**Issue by vapadwal** [oasp/oasp4j#672]
LoginController#login in the application template has @RequestMapping(value = "/login**", method = RequestMethod.GET) which *fails* with the Angular 6 template as this uses POST for login

Changes required in LoginController
RequestMapping(value = "/login**", method = { RequestMethod.POST })

**Comment by ivanderk** [comment]
This might break existing code on the client side as people might had to change their *client* in order to send a GET request. Why not supporting both?

`
RequestMapping(value = "/login**", method = { RequestMethod.GET, RequestMethod.POST})
`

**Comment by hohwille** [comment]
@ivanderk thanks for your smart suggestion :)

**Comment by hohwille** [comment]
PR #678 was merged, hence done.
