### ISSUE TITLE
Spring boot upgrade issue with postgresql

### ISSUE THREAD

**Issue by vapadwal** [oasp/oasp4j#680]
Basically this issue extension to issue https://github.com/oasp/oasp4j/issues/674 , 

It includes review suggested in PR https://github.com/oasp/oasp4j/pull/677 and also the issue related to postgres.
Below is the exception we were getting for postgres,

Caused by: java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.

**Comment by hohwille** [comment]
Solved like #674 with PR #679
