### ISSUE TITLE
Archetype 3.0.0 provides wrong oracle maven dependency

### ISSUE THREAD

**Issue by maybeec** [oasp/oasp4j#685]
Generating a new application with oracle as database setup, you will end up in a non-compiling application as the groupId of the oracle driver specified in maven pom is not correct.

**Comment by maybeec** [comment]
It's up to the user how he uploaded the oracle driver dependency into the nexus. Seems, that my client messed up here.

**Comment by hohwille** [comment]
For the record: We had discussions about this and changed the GAV to the offical coordinates from Oracle:
https://docs.oracle.com/middleware/1213/core/MAVEN/config_maven_repo.htm#MAVEN9016
