### ISSUE TITLE
Logging in archetype 3.0.0 buggy

### ISSUE THREAD

**Issue by maybeec** [oasp/oasp4j#687]
I observed strange behavior with the logging when starting the archetype as a SpringBoot application within eclipse. The simplest steps to reproduce the issue is download a new non-oomph eclipse package directly from the eclipse website, extract it, create a new workspace and create a new project from oasp4j 3.0.0 archetype. Start the SprintBoot app. For me it always says:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

Although it should work, as I checked, that logback-classic is correctly included.
I am using Java 1.8.181

**Comment by hohwille** [comment]
@maybeec can you confirm that this issue is invalid?
If I am not mistaken, this was related to our debugging where we found out that have did download a corrupted JAR in your repo. If so there is not error related to this in oasp and we can close this issue.

**Comment by hohwille** [comment]
I am closing this. In case something is wrong, please reopen.

**Comment by maybeec** [comment]
Sry, I forgot to close that issue again. This was about this strange issue of a corrupt logback jar in my maven repository.
