### ISSUE TITLE
Enable staging of oasp artifacts to maven central.

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j#80]
We need to follow OSSRH process to enable staging of our modules to maven central repo:
http://central.sonatype.org/pages/ossrh-guide.html

**Comment by hohwille** [comment]
> No public key: Key with id: (6966663c6e7ec74f) was not able to be located on http://keyserver.ubuntu.com:11371. Upload your public key and try the operation again.

IMHO auto publication after gpg key creation seemed to have failed. I fixed this now by submitting the key by hand.

> Invalid POM: /io/oasp/java/templates/oasp4j-template-server/1.0.0/oasp4j-template-server-1.0.0.pom: Developer information missing

So we are really forced to list the developers in our POMs. Shall we invite all developers to add themselves to this list in our top-level POM? Or should we just list a single user to fullfill this otherwise pointless requirement and forget about the rest?

**Comment by sobkowiak** [comment]
It's good idea to invite all active developers to make an `developer` entry in the main pom. But now you can simply enable [this](https://github.com/oasp/oasp4j/blob/develop/pom.xml#L484-L499) block again to avoid the problems with release

**Comment by hohwille** [comment]
OK:

https://oss.sonatype.org/content/repositories/iooasp-1002/

I will give the community a little time to test the release. I will also test it and see that it is working alright.

**Comment by hohwille** [comment]
Shall we use the common voting with lazy consensus via our dev list?
I think this is the best approach...

**Comment by hohwille** [comment]
I already found a small bug and reopened #15.

**Comment by sobkowiak** [comment]
> Shall we use the common voting with lazy consensus via our dev list?
I think this is the best approach...

:+1:  I think it's a good idea. In Apache we have usually 72 hours for the vote.

**Comment by hohwille** [comment]
Next try:
https://oss.sonatype.org/content/repositories/iooasp-1003/

**Comment by hohwille** [comment]
Staging completed:
http://repo1.maven.org/maven2/io/oasp/java/
