### ISSUE TITLE
OWASP A4: Insecure Direct Object References

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j#86]
OWASP A4:
https://www.owasp.org/index.php/Top_10_2013-A4-Insecure_Direct_Object_References

We are not generally avoiding direct object references and that is for good reason.
But we have to outline the impact and ensure the awareness of the problems.
This means that we have to ensure that authorization is bullet proof so a simple REST serivce
https://.../entity/4711
will only reveal data the actual user is permitted to see. This is obvious for us but the OASP has to make this explicit and there are constellations where this gets complicated (e.g. if you retrieve an address entity by ID but that one belongs to a business entity that is restricted for specific users. Even though the service may not need the parent entity for the result he has to ensure the data-authorization is verified. We should also give guidelines for design alternatives to avoid such problems at all).

**Comment by hohwille** [comment]
We have already done the same in our sample with the BLOB services: Instead of writing a generic service for all BLOBs, we write individual services that can check permissions based on the parent business object.
We still need to explain this easily as best practice what might be the biggest challenge.

**Comment by marpuch** [comment]
Just a little clarification. OWASP says, that 'insecure direct object references' are bad. To be bad, they must be both 'insecure' and 'direct' at the same time.

If the authorization is 'bullet proof' we will have 'secure direct object references' which are ok. 

Personally I don't like the idea of 'insecure indirect object references (just like links to youtube or picasa albums, which contain a secret. If you know the secret, you can access the resource). You could achieve such thing well using OWASP ESAPI, but this solution still has issues.

'secure indirect object references' are imho a waste of time.

**Comment by hohwille** [comment]
:+1: thanks for the clarification. We should reflect this in our documentation. Great that we agree on a common strategy - I am fully with you.

**Comment by hohwille** [comment]
I am not a big fan of OWASP ESAPI. I think the OWASP team does a really good job on documenting vulnerabilities and explaining them and what you can do. However, they are probably not the most excellent coding community. E.g. to prevent log forging I do not have to provide my own logger API. Similar things for other areas. That is really old-fashioned style. However, we might integrate some parts of ESAPI when it makes sense. If you have good suggestions let us know.

**Comment by MarcoRose** [comment]
TODO: documentation of OASP regarding OWASP

**Comment by hohwille** [comment]
I added this to the documentation and consider it as done. Improvements to the documentation are still welcome:
https://github.com/oasp-forge/oasp4j-wiki/wiki/guide-logic-layer#direct-object-references
